// CCCC_FLAGS: -c=generated -o /dev/stdout
// CCCC_EXPECT_STDOUT: Generated by CCCC
// CCCC_REJECT_STDERR: failed to link programs
//
// Ticket #1266: a translation unit that emits nothing from comptime (no
// published node, no generated global) *and* defines no ordinary function
// parsed to an empty global list, which cc_link_progs reports as NULL. The
// driver treated that as "failed to link programs" -- printed the error,
// wrote no file, and (separately) still exited 0. `-c=generated` now
// serializes such a TU to a valid near-empty file (banner plus any
// auto-captured directive) instead. The comptime code still runs; its
// stdout ("42") is not asserted here since it interleaves with the
// serialized output written to the same fd.

#include @comptime <stdio.h>

[[cccc::comptime]]
int helper_1266(int x) {
    return x * 2;
}

[[cccc::comptime]]
void gen_1266(void) {
    printf("%d\n", helper_1266(21));
}

gen_1266();
