/* config.h -- Hand-written for CCCC (no autoconf).
   Covers macOS (arm64/x86_64) and Linux (x86_64/aarch64).
   Generated by configure.ac on other platforms; this file replaces it. */

/* ELF size: 64-bit on all supported targets. */
#if defined(__linux__)
# define BACKTRACE_ELF_SIZE 64
#endif

/* Use __atomic builtins (Clang/GCC on all CCCC targets). */
#define HAVE_ATOMIC_FUNCTIONS 1

/* __sync_* builtins are also available; required by state.c to enable the
 * threaded path.  (HAVE_ATOMIC_FUNCTIONS takes precedence in internal.h, so
 * the __sync_* macros are never actually used — but this define must be
 * present for the threading gate in state.c to open.) */
#define HAVE_SYNC_FUNCTIONS 1

/* fcntl(2) is available on POSIX. */
#define HAVE_FCNTL 1

/* dl_iterate_phdr is available on Linux (glibc/musl). */
#if defined(__linux__)
# define HAVE_DL_ITERATE_PHDR 1
# define HAVE_LINK_H 1
#endif

/* _Unwind_GetIPInfo is provided by the Clang/GCC runtime on both platforms. */
#define HAVE_GETIPINFO 1

/* mmap(2) is available everywhere we target. */
#define HAVE_SYS_MMAN_H 1

/* strnlen is declared in <string.h> on POSIX. */
#define HAVE_DECL_STRNLEN 1

/* Mach-O / dyld path API (macOS only). */
#if defined(__APPLE__)
# define HAVE_MACH_O_DYLD_H 1
#endif

/* Standard POSIX headers present on all targets. */
#define HAVE_DLFCN_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_LSTAT 1
#define HAVE_READLINK 1
#define STDC_HEADERS 1

/* lzma / zlib / zstd decompression — not needed for our use case. */
/* #undef HAVE_LIBLZMA */
/* #undef HAVE_ZLIB */
/* #undef HAVE_ZSTD */
