/* decimal_math.h - <math.h> transcendentals for _Decimal32/64/128 (C23,
 * tracker #828, phase 2 of #402). bid{32,64,128}_{sqrt,exp,log,pow,sin,
 * cos,...} via the Intel BID library, opt-in with CCCC_HAS_DECIMAL=1 (see
 * man/VM.md's Decimal Floating-Point section).
 *
 * This entire header is a compile error without CCCC_HAS_DECIMAL: unlike
 * <math.h>'s binary-float functions, there is no fallback here (real
 * decimal arithmetic is opt-in in the first place -- see decimal.c's
 * top-of-file comment for the "no lossy emulation" rationale, same as
 * #824's POSIX policy).
 *
 * Every function below is a thin static inline wrapper around one of six
 * op-dispatch entry points (src/stdlib/decimal_math.c's __cccc_dec_math1/
 * math2/math3/mathi/mathn/mathp), each taking raw addresses so no BID type
 * has to appear here. Op numbers below MUST stay in sync with that file's
 * enums -- there is no shared header between the compiler-internal .c and
 * this guest-facing one, so a mismatch here is a silent miscompile.
 */
#ifndef __DECIMAL_MATH_H
#define __DECIMAL_MATH_H

#ifdef __STDC_IEC_60559_DFP__

extern long long __cccc_dec_math1(long long op, long long w, long long dst, long long a);
extern long long __cccc_dec_math2(long long op, long long w, long long dst, long long a, long long b);
extern long long __cccc_dec_math3(long long op, long long w, long long dst, long long a, long long b, long long c);
extern long long __cccc_dec_mathi(long long op, long long w, long long a, long long b);
extern long long __cccc_dec_mathn(long long op, long long w, long long dst, long long a, long long n);
extern long long __cccc_dec_mathp(long long op, long long w, long long dst, long long a, long long outp);

/* -- op numbers (mirrored in src/stdlib/decimal_math.c) ------------------ */

#define __CCCC_DECM1_SQRT      1
#define __CCCC_DECM1_CBRT      2
#define __CCCC_DECM1_EXP       3
#define __CCCC_DECM1_EXP2      4
#define __CCCC_DECM1_EXP10     5
#define __CCCC_DECM1_EXPM1     6
#define __CCCC_DECM1_LOG       7
#define __CCCC_DECM1_LOG2      8
#define __CCCC_DECM1_LOG10     9
#define __CCCC_DECM1_LOG1P     10
#define __CCCC_DECM1_SIN       11
#define __CCCC_DECM1_COS       12
#define __CCCC_DECM1_TAN       13
#define __CCCC_DECM1_ASIN      14
#define __CCCC_DECM1_ACOS      15
#define __CCCC_DECM1_ATAN      16
#define __CCCC_DECM1_SINH      17
#define __CCCC_DECM1_COSH      18
#define __CCCC_DECM1_TANH      19
#define __CCCC_DECM1_ASINH     20
#define __CCCC_DECM1_ACOSH     21
#define __CCCC_DECM1_ATANH     22
#define __CCCC_DECM1_ERF       23
#define __CCCC_DECM1_ERFC      24
#define __CCCC_DECM1_LGAMMA    25
#define __CCCC_DECM1_TGAMMA    26
#define __CCCC_DECM1_CEIL      27
#define __CCCC_DECM1_FLOOR     28
#define __CCCC_DECM1_TRUNC     29
#define __CCCC_DECM1_ROUND     30
#define __CCCC_DECM1_NEARBYINT 31
#define __CCCC_DECM1_RINT      32
#define __CCCC_DECM1_LOGB      33
#define __CCCC_DECM1_QUANTUM   34
#define __CCCC_DECM1_FABS      35

#define __CCCC_DECM2_POW        1
#define __CCCC_DECM2_ATAN2      2
#define __CCCC_DECM2_HYPOT      3
#define __CCCC_DECM2_FDIM       4
#define __CCCC_DECM2_QUANTIZE   5
#define __CCCC_DECM2_FMOD       6
#define __CCCC_DECM2_REMAINDER  7
#define __CCCC_DECM2_FMIN       8
#define __CCCC_DECM2_FMAX       9
#define __CCCC_DECM2_NEXTAFTER  10
#define __CCCC_DECM2_COPYSIGN   11
#define __CCCC_DECM2_NEXTTOWARD 12

#define __CCCC_DECM3_FMA 1

#define __CCCC_DECMI_ISNAN       1
#define __CCCC_DECMI_ISINF       2
#define __CCCC_DECMI_ISFINITE    3
#define __CCCC_DECMI_ISNORMAL    4
#define __CCCC_DECMI_ISSIGNALING 5
#define __CCCC_DECMI_SIGNBIT     6
#define __CCCC_DECMI_FPCLASSIFY  7
#define __CCCC_DECMI_ILOGB       8
#define __CCCC_DECMI_QUANTEXP    9
#define __CCCC_DECMI_LRINT       10
#define __CCCC_DECMI_LLRINT      11
#define __CCCC_DECMI_LROUND      12
#define __CCCC_DECMI_LLROUND     13
#define __CCCC_DECMI_SAMEQUANTUM 14
#define __CCCC_DECMI_TOTALORDER  15

#define __CCCC_DECMN_SCALBN  1
#define __CCCC_DECMN_SCALBLN 2
#define __CCCC_DECMN_LDEXP   3

#define __CCCC_DECMP_FREXP 1
#define __CCCC_DECMP_MODF  2

/* -- per-width typed wrappers, generated by X-macro over 32/64/128 ------- */

#define __CCCC_DECM_UNARY(FN, OP, TY, W) \
    static inline TY FN(TY x) { \
        TY xx = x, r; \
        __cccc_dec_math1(OP, W, (long long)&r, (long long)&xx); \
        return r; \
    }

#define __CCCC_DECM_BINARY(FN, OP, TY, W) \
    static inline TY FN(TY x, TY y) { \
        TY xx = x, yy = y, r; \
        __cccc_dec_math2(OP, W, (long long)&r, (long long)&xx, (long long)&yy); \
        return r; \
    }

#define __CCCC_DECM_TERNARY(FN, OP, TY, W) \
    static inline TY FN(TY x, TY y, TY z) { \
        TY xx = x, yy = y, zz = z, r; \
        __cccc_dec_math3(OP, W, (long long)&r, (long long)&xx, (long long)&yy, (long long)&zz); \
        return r; \
    }

#define __CCCC_DECM_PRED(FN, OP, TY, W) \
    static inline int FN(TY x) { \
        TY xx = x; \
        return (int)__cccc_dec_mathi(OP, W, (long long)&xx, 0); \
    }

#define __CCCC_DECM_PRED2(FN, OP, TY, W) \
    static inline int FN(TY x, TY y) { \
        TY xx = x, yy = y; \
        return (int)__cccc_dec_mathi(OP, W, (long long)&xx, (long long)&yy); \
    }

#define __CCCC_DECM_TOLONG(FN, OP, TY, W) \
    static inline long FN(TY x) { \
        TY xx = x; \
        return (long)__cccc_dec_mathi(OP, W, (long long)&xx, 0); \
    }

#define __CCCC_DECM_TOLLONG(FN, OP, TY, W) \
    static inline long long FN(TY x) { \
        TY xx = x; \
        return __cccc_dec_mathi(OP, W, (long long)&xx, 0); \
    }

#define __CCCC_DECM_TOINT(FN, OP, TY, W) \
    static inline int FN(TY x) { \
        TY xx = x; \
        return (int)__cccc_dec_mathi(OP, W, (long long)&xx, 0); \
    }

#define __CCCC_DECM_SCALE(FN, OP, TY, W) \
    static inline TY FN(TY x, int n) { \
        TY xx = x, r; \
        __cccc_dec_mathn(OP, W, (long long)&r, (long long)&xx, (long long)n); \
        return r; \
    }

#define __CCCC_DECM_SCALEL(FN, OP, TY, W) \
    static inline TY FN(TY x, long n) { \
        TY xx = x, r; \
        __cccc_dec_mathn(OP, W, (long long)&r, (long long)&xx, (long long)n); \
        return r; \
    }

/* __cccc_dec_mathp's FREXP case writes the exponent through outp as a
 * plain `int` (not `long long`) -- `e` here is only sized `long long` so
 * its address is a valid outp for the shared long-long-typed entry point.
 * That means the write only ever touches e's low 4 bytes, and `(int)e`
 * below only ever reads them back -- correct on the little-endian targets
 * this project builds for (aarch64/x86_64, per man/COVERAGE.md), not
 * portable to a big-endian host without widening the write. */
#define __CCCC_DECM_FREXP(FN, TY, W) \
    static inline TY FN(TY x, int *exp) { \
        TY xx = x, r; \
        long long e = 0; \
        __cccc_dec_mathp(__CCCC_DECMP_FREXP, W, (long long)&r, (long long)&xx, (long long)&e); \
        *exp = (int)e; \
        return r; \
    }

#define __CCCC_DECM_MODF(FN, TY, W) \
    static inline TY FN(TY x, TY *iptr) { \
        TY xx = x, r, ip; \
        __cccc_dec_mathp(__CCCC_DECMP_MODF, W, (long long)&r, (long long)&xx, (long long)&ip); \
        *iptr = ip; \
        return r; \
    }

/* nexttoward's second argument is always _Decimal128, regardless of the
 * first argument's width -- matches C's nexttoward(x, long double) shape,
 * with _Decimal128 standing in for "widest". */
#define __CCCC_DECM_NEXTTOWARD(FN, TY, W) \
    static inline TY FN(TY x, _Decimal128 y) { \
        TY xx = x, r; \
        _Decimal128 yy = y; \
        __cccc_dec_math2(__CCCC_DECM2_NEXTTOWARD, W, (long long)&r, (long long)&xx, (long long)&yy); \
        return r; \
    }

#define __CCCC_DECM_ALL_UNARY(SFX, TY, W) \
    __CCCC_DECM_UNARY(sqrt##SFX, __CCCC_DECM1_SQRT, TY, W) \
    __CCCC_DECM_UNARY(cbrt##SFX, __CCCC_DECM1_CBRT, TY, W) \
    __CCCC_DECM_UNARY(exp##SFX, __CCCC_DECM1_EXP, TY, W) \
    __CCCC_DECM_UNARY(exp2##SFX, __CCCC_DECM1_EXP2, TY, W) \
    __CCCC_DECM_UNARY(exp10##SFX, __CCCC_DECM1_EXP10, TY, W) \
    __CCCC_DECM_UNARY(expm1##SFX, __CCCC_DECM1_EXPM1, TY, W) \
    __CCCC_DECM_UNARY(log##SFX, __CCCC_DECM1_LOG, TY, W) \
    __CCCC_DECM_UNARY(log2##SFX, __CCCC_DECM1_LOG2, TY, W) \
    __CCCC_DECM_UNARY(log10##SFX, __CCCC_DECM1_LOG10, TY, W) \
    __CCCC_DECM_UNARY(log1p##SFX, __CCCC_DECM1_LOG1P, TY, W) \
    __CCCC_DECM_UNARY(sin##SFX, __CCCC_DECM1_SIN, TY, W) \
    __CCCC_DECM_UNARY(cos##SFX, __CCCC_DECM1_COS, TY, W) \
    __CCCC_DECM_UNARY(tan##SFX, __CCCC_DECM1_TAN, TY, W) \
    __CCCC_DECM_UNARY(asin##SFX, __CCCC_DECM1_ASIN, TY, W) \
    __CCCC_DECM_UNARY(acos##SFX, __CCCC_DECM1_ACOS, TY, W) \
    __CCCC_DECM_UNARY(atan##SFX, __CCCC_DECM1_ATAN, TY, W) \
    __CCCC_DECM_UNARY(sinh##SFX, __CCCC_DECM1_SINH, TY, W) \
    __CCCC_DECM_UNARY(cosh##SFX, __CCCC_DECM1_COSH, TY, W) \
    __CCCC_DECM_UNARY(tanh##SFX, __CCCC_DECM1_TANH, TY, W) \
    __CCCC_DECM_UNARY(asinh##SFX, __CCCC_DECM1_ASINH, TY, W) \
    __CCCC_DECM_UNARY(acosh##SFX, __CCCC_DECM1_ACOSH, TY, W) \
    __CCCC_DECM_UNARY(atanh##SFX, __CCCC_DECM1_ATANH, TY, W) \
    __CCCC_DECM_UNARY(erf##SFX, __CCCC_DECM1_ERF, TY, W) \
    __CCCC_DECM_UNARY(erfc##SFX, __CCCC_DECM1_ERFC, TY, W) \
    __CCCC_DECM_UNARY(lgamma##SFX, __CCCC_DECM1_LGAMMA, TY, W) \
    __CCCC_DECM_UNARY(tgamma##SFX, __CCCC_DECM1_TGAMMA, TY, W) \
    __CCCC_DECM_UNARY(ceil##SFX, __CCCC_DECM1_CEIL, TY, W) \
    __CCCC_DECM_UNARY(floor##SFX, __CCCC_DECM1_FLOOR, TY, W) \
    __CCCC_DECM_UNARY(trunc##SFX, __CCCC_DECM1_TRUNC, TY, W) \
    __CCCC_DECM_UNARY(round##SFX, __CCCC_DECM1_ROUND, TY, W) \
    __CCCC_DECM_UNARY(nearbyint##SFX, __CCCC_DECM1_NEARBYINT, TY, W) \
    __CCCC_DECM_UNARY(rint##SFX, __CCCC_DECM1_RINT, TY, W) \
    __CCCC_DECM_UNARY(logb##SFX, __CCCC_DECM1_LOGB, TY, W) \
    __CCCC_DECM_UNARY(quantum##SFX, __CCCC_DECM1_QUANTUM, TY, W) \
    __CCCC_DECM_UNARY(fabs##SFX, __CCCC_DECM1_FABS, TY, W) \
    \
    __CCCC_DECM_BINARY(pow##SFX, __CCCC_DECM2_POW, TY, W) \
    __CCCC_DECM_BINARY(atan2##SFX, __CCCC_DECM2_ATAN2, TY, W) \
    __CCCC_DECM_BINARY(hypot##SFX, __CCCC_DECM2_HYPOT, TY, W) \
    __CCCC_DECM_BINARY(fdim##SFX, __CCCC_DECM2_FDIM, TY, W) \
    __CCCC_DECM_BINARY(quantize##SFX, __CCCC_DECM2_QUANTIZE, TY, W) \
    __CCCC_DECM_BINARY(fmod##SFX, __CCCC_DECM2_FMOD, TY, W) \
    __CCCC_DECM_BINARY(remainder##SFX, __CCCC_DECM2_REMAINDER, TY, W) \
    __CCCC_DECM_BINARY(fmin##SFX, __CCCC_DECM2_FMIN, TY, W) \
    __CCCC_DECM_BINARY(fmax##SFX, __CCCC_DECM2_FMAX, TY, W) \
    __CCCC_DECM_BINARY(nextafter##SFX, __CCCC_DECM2_NEXTAFTER, TY, W) \
    __CCCC_DECM_BINARY(copysign##SFX, __CCCC_DECM2_COPYSIGN, TY, W) \
    __CCCC_DECM_NEXTTOWARD(nexttoward##SFX, TY, W) \
    \
    __CCCC_DECM_TERNARY(fma##SFX, __CCCC_DECM3_FMA, TY, W) \
    \
    __CCCC_DECM_PRED(isnan##SFX, __CCCC_DECMI_ISNAN, TY, W) \
    __CCCC_DECM_PRED(isinf##SFX, __CCCC_DECMI_ISINF, TY, W) \
    __CCCC_DECM_PRED(isfinite##SFX, __CCCC_DECMI_ISFINITE, TY, W) \
    __CCCC_DECM_PRED(isnormal##SFX, __CCCC_DECMI_ISNORMAL, TY, W) \
    __CCCC_DECM_PRED(issignaling##SFX, __CCCC_DECMI_ISSIGNALING, TY, W) \
    __CCCC_DECM_PRED(signbit##SFX, __CCCC_DECMI_SIGNBIT, TY, W) \
    __CCCC_DECM_TOINT(fpclassify##SFX, __CCCC_DECMI_FPCLASSIFY, TY, W) \
    __CCCC_DECM_TOINT(ilogb##SFX, __CCCC_DECMI_ILOGB, TY, W) \
    __CCCC_DECM_TOINT(quantexp##SFX, __CCCC_DECMI_QUANTEXP, TY, W) \
    __CCCC_DECM_TOLONG(lrint##SFX, __CCCC_DECMI_LRINT, TY, W) \
    __CCCC_DECM_TOLLONG(llrint##SFX, __CCCC_DECMI_LLRINT, TY, W) \
    __CCCC_DECM_TOLONG(lround##SFX, __CCCC_DECMI_LROUND, TY, W) \
    __CCCC_DECM_TOLLONG(llround##SFX, __CCCC_DECMI_LLROUND, TY, W) \
    __CCCC_DECM_PRED2(samequantum##SFX, __CCCC_DECMI_SAMEQUANTUM, TY, W) \
    __CCCC_DECM_PRED2(totalorder##SFX, __CCCC_DECMI_TOTALORDER, TY, W) \
    \
    __CCCC_DECM_SCALE(scalbn##SFX, __CCCC_DECMN_SCALBN, TY, W) \
    __CCCC_DECM_SCALEL(scalbln##SFX, __CCCC_DECMN_SCALBLN, TY, W) \
    __CCCC_DECM_SCALE(ldexp##SFX, __CCCC_DECMN_LDEXP, TY, W) \
    \
    __CCCC_DECM_FREXP(frexp##SFX, TY, W) \
    __CCCC_DECM_MODF(modf##SFX, TY, W)

__CCCC_DECM_ALL_UNARY(d32, _Decimal32, 0)
__CCCC_DECM_ALL_UNARY(d64, _Decimal64, 1)
__CCCC_DECM_ALL_UNARY(d128, _Decimal128, 2)

#undef __CCCC_DECM_ALL_UNARY
#undef __CCCC_DECM_UNARY
#undef __CCCC_DECM_BINARY
#undef __CCCC_DECM_TERNARY
#undef __CCCC_DECM_PRED
#undef __CCCC_DECM_PRED2
#undef __CCCC_DECM_TOLONG
#undef __CCCC_DECM_TOLLONG
#undef __CCCC_DECM_TOINT
#undef __CCCC_DECM_SCALE
#undef __CCCC_DECM_SCALEL
#undef __CCCC_DECM_FREXP
#undef __CCCC_DECM_MODF
#undef __CCCC_DECM_NEXTTOWARD

#endif /* __STDC_IEC_60559_DFP__ */

#endif /* __DECIMAL_MATH_H */
