/*
 CCCC: Comprehensiev C Compensation Compiler

 Copyright (C) 2025 George Watson

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#include "cccc.h"
#include "./internal.h"
#include <limits.h>

//
// Bytecode Optimizer
//
// This module implements optional optimization passes on the generated bytecode.
// The optimizer runs after codegen and before execution, operating on the
// text_seg[] array of instructions.
//
// Optimization Levels:
//   -O0: No optimization (default)
//   -O1: Basic - constant folding
//   -O2: Standard - constant folding + peephole
//   -O3: Aggressive - all passes including dead code elimination
//

// ========== Helper Functions ==========

// Get opcode from instruction at pc
static int get_opcode(CCCC *vm, CCCCPc pc) {
    return (int)vm->text_seg[pc];
}

static int get_instr_size(int op) {
    return cc_instr_words(op);
}

static int get_instr_size_at(CCCC *vm, CCCCPc pc, CCCCPc end) {
    int op = get_opcode(vm, pc);
    int size = get_instr_size(op);
    if (op == JMPT && pc + 3 < end) {
        CCCCPc table_pc = vm->text_seg[pc + 1];
        CCCCInstrWord count = vm->text_seg[pc + 2];
        if (table_pc == pc + 4 && table_pc + (CCCCPc)count <= end)
            size += (int)count;
    }
    return size;
}

static int get_compacted_instr_size_at(CCCC *vm, CCCCPc pc, CCCCPc end) {
    int op = get_opcode(vm, pc);
    int size = get_instr_size(op);
    if (op == JMPT && pc + 3 < end) {
        CCCCInstrWord count = vm->text_seg[pc + 2];
        if (pc + 4 + (CCCCPc)count <= end)
            size += (int)count;
    }
    return size;
}

typedef struct {
    bool active;
    int nwords;
    CCCCInstrWord words[4];
} OptReplacement;

static void set_li_replacement(OptReplacement *repls, CCCCPc pc, int rd,
                               long long imm) {
    repls[pc].active = true;
    repls[pc].nwords = 4;
    repls[pc].words[0] = LI3;
    repls[pc].words[1] = ENCODE_R(rd);
    repls[pc].words[2] = cc_i64_lo(imm);
    repls[pc].words[3] = cc_i64_hi(imm);
}

static bool is_nop_at(CCCC *vm, CCCCPc pc) {
    int op = get_opcode(vm, pc);
    if (op == MOV3) {
        int rd = vm->text_seg[pc + 1] & 0xFF;
        int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
        return rd == REG_ZERO && rs == REG_ZERO;
    }
    if (op == LI3) {
        int rd = vm->text_seg[pc + 1] & 0xFF;
        return rd == REG_ZERO && cc_read_i64_at(vm, pc + 2) == 0;
    }
    return false;
}

static bool li_matches_replacement(CCCC *vm, CCCCPc pc,
                                   const OptReplacement *repl) {
    if (!repl->active || repl->nwords != 4 || repl->words[0] != LI3)
        return false;
    if (get_opcode(vm, pc) != LI3)
        return false;
    return vm->text_seg[pc + 1] == repl->words[1] &&
           vm->text_seg[pc + 2] == repl->words[2] &&
           vm->text_seg[pc + 3] == repl->words[3];
}

static CCCCPc remap_pc(CCCCPc *pc_map, CCCCPc old_end, CCCCPc target) {
    if (target == CCCC_INVALID_PC)
        return target;
    if (target <= old_end)
        return pc_map[target];
    return target;
}

static void remap_text_byte_offset_at(CCCC *vm, CCCCPc operand_pc,
                                      CCCCPc *pc_map, CCCCPc old_end) {
    long long old_offset = cc_read_i64_at(vm, operand_pc);
    CCCCPc old_target = cc_byte_offset_to_pc(old_offset);
    if (old_target == CCCC_INVALID_PC)
        return;
    CCCCPc new_target = remap_pc(pc_map, old_end, old_target);
    if (new_target != CCCC_INVALID_PC)
        cc_write_i64_at(vm, operand_pc, cc_pc_to_byte_offset(new_target));
}

static void remap_function_metadata(Obj *obj, CCCCPc *pc_map, CCCCPc old_end) {
    for (; obj; obj = obj->next) {
        if (obj->is_function) {
            if (obj->code_addr >= 0) {
                CCCCPc pc = (CCCCPc)obj->code_addr;
                if (pc <= old_end)
                    obj->code_addr = remap_pc(pc_map, old_end, pc);
            }
            if (obj->code_end_addr >= 0) {
                CCCCPc pc = (CCCCPc)obj->code_end_addr;
                if (pc <= old_end)
                    obj->code_end_addr = remap_pc(pc_map, old_end, pc);
            }
        }
    }
}

static void mark_text_target(CCCC *vm, bool *targets, CCCCPc start,
                             CCCCPc end, CCCCPc target) {
    (void)vm;
    if (target >= start && target < end)
        targets[target - start] = true;
}

static bool *build_control_flow_targets(CCCC *vm, CCCCPc start,
                                        CCCCPc end) {
    size_t count = (size_t)(end - start + 1);
    bool *targets = calloc(count, sizeof(bool));
    if (!targets)
        error("out of memory");

    for (CCCCPc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);
        if (size <= 0)
            break;

        if (op == JMP || op == CALL || op == CALLT) {
            mark_text_target(vm, targets, start, end, vm->text_seg[pc + 1]);
        } else if (op == JZ3 || op == JNZ3) {
            mark_text_target(vm, targets, start, end, vm->text_seg[pc + 2]);
        } else if (op == JMPT && pc + 3 < end) {
            CCCCPc table_pc = vm->text_seg[pc + 1];
            CCCCInstrWord count = vm->text_seg[pc + 2];
            mark_text_target(vm, targets, start, end, vm->text_seg[pc + 3]);
            if (table_pc + (CCCCPc)count <= end) {
                for (CCCCInstrWord i = 0; i < count; i++)
                    mark_text_target(vm, targets, start, end,
                                     vm->text_seg[table_pc + (CCCCPc)i]);
            }
        } else if (op == LTA3) {
            CCCCPc target = cc_byte_offset_to_pc(cc_read_i64_at(vm, pc + 2));
            mark_text_target(vm, targets, start, end, target);
        }

        pc += size;
    }

    return targets;
}

// ========== Pass 1: Constant Folding ==========
//
// Fold arithmetic operations on constant values at compile time.
// Pattern: LI3 rx, A; LI3 ry, B; OP3 rz, rx, ry -> LI3 rz, (A OP B)
//
// We use a simple value tracking approach:
// - Track which registers hold known constant values
// - When we see an arithmetic op with two constant operands, fold it
// - Replace the instruction sequence with a single LI3
//

// Maximum registers to track
#define MAX_TRACKED_REGS 32

// Track constant values in registers
typedef struct {
    bool is_const[MAX_TRACKED_REGS];
    long long value[MAX_TRACKED_REGS];
} RegState;

// Reset register state (e.g., at function boundaries, jumps)
static void reset_reg_state(RegState *state) {
    for (int i = 0; i < MAX_TRACKED_REGS; i++) {
        state->is_const[i] = false;
        state->value[i] = 0;
    }
    state->is_const[REG_ZERO] = true;
    state->value[REG_ZERO] = 0;
}

static void set_const_reg(RegState *state, int rd, long long value) {
    if (rd <= REG_ZERO || rd >= MAX_TRACKED_REGS)
        return;
    state->is_const[rd] = true;
    state->value[rd] = value;
}

static void invalidate_reg(RegState *state, int rd) {
    if (rd <= REG_ZERO || rd >= MAX_TRACKED_REGS)
        return;
    state->is_const[rd] = false;
    state->value[rd] = 0;
}

static bool add_overflows(long long a, long long b) {
    return (b > 0 && a > LLONG_MAX - b) ||
           (b < 0 && a < LLONG_MIN - b);
}

static bool sub_overflows(long long a, long long b) {
    return (b < 0 && a > LLONG_MAX + b) ||
           (b > 0 && a < LLONG_MIN + b);
}

static bool mul_overflows(long long a, long long b) {
#if defined(__has_builtin)
#if __has_builtin(__builtin_mul_overflow)
    long long result;
    return __builtin_mul_overflow(a, b, &result);
#endif
#endif
    if (a > 0) {
        if (b > 0)
            return a > LLONG_MAX / b;
        return b < LLONG_MIN / a;
    }
    if (a < 0) {
        if (b > 0)
            return a < LLONG_MIN / b;
        return a != 0 && b < LLONG_MAX / a;
    }
    return false;
}

static bool eval_binary_const(int op, long long a, long long b,
                              bool preserve_overflow_traps,
                              long long *out) {
    (void)preserve_overflow_traps;
    switch (op) {
        case ADD3:
            *out = (long long)((unsigned long long)a + (unsigned long long)b);
            return true;
        case ADDC:
            if (add_overflows(a, b))
                return false;
            *out = a + b;
            return true;
        case SUB3:
            *out = (long long)((unsigned long long)a - (unsigned long long)b);
            return true;
        case SUBC:
            if (sub_overflows(a, b))
                return false;
            *out = a - b;
            return true;
        case MUL3:
            *out = (long long)((unsigned long long)a * (unsigned long long)b);
            return true;
        case MULC:
            if (mul_overflows(a, b))
                return false;
            *out = a * b;
            return true;
        case DIV3:
            if (b == 0)
                return false;
            *out = (a == LLONG_MIN && b == -1) ? LLONG_MIN : a / b;
            return true;
        case DIVC:
            if (b == 0 || (a == LLONG_MIN && b == -1))
                return false;
            *out = a / b;
            return true;
        case UDIV3:
            if (b == 0)
                return false;
            *out = (long long)((unsigned long long)a / (unsigned long long)b);
            return true;
        case MOD3:
            if (b == 0 || (a == LLONG_MIN && b == -1))
                return false;
            *out = a % b;
            return true;
        case UMOD3:
            if (b == 0)
                return false;
            *out = (long long)((unsigned long long)a % (unsigned long long)b);
            return true;
        case AND3:
            *out = a & b;
            return true;
        case OR3:
            *out = a | b;
            return true;
        case XOR3:
            *out = a ^ b;
            return true;
        case SHL3:
            if (b < 0 || b >= 63 || a < 0 || a > (LLONG_MAX >> b))
                return false;
            *out = a << b;
            return true;
        case SHR3:
            if (b < 0 || b >= 64 || a < 0)
                return false;
            *out = a >> b;
            return true;
        case USHR3:
            if (b < 0 || b >= 64)
                return false;
            *out = (long long)((unsigned long long)a >> b);
            return true;
        case SEQ3:
            *out = (a == b) ? 1 : 0;
            return true;
        case SNE3:
            *out = (a != b) ? 1 : 0;
            return true;
        case SLT3:
            *out = (a < b) ? 1 : 0;
            return true;
        case SGE3:
            *out = (a >= b) ? 1 : 0;
            return true;
        case SGT3:
            *out = (a > b) ? 1 : 0;
            return true;
        case SLE3:
            *out = (a <= b) ? 1 : 0;
            return true;
        default:
            return false;
    }
}

static bool eval_unary_const(int op, long long value, long long *out) {
    switch (op) {
        case NEG3:
            if (value == LLONG_MIN)
                return false;
            *out = -value;
            return true;
        case NOT3:
            *out = !value;
            return true;
        case BNOT3:
            *out = ~value;
            return true;
        default:
            return false;
    }
}

static bool eval_extend_const(int op, long long value, long long *out) {
    switch (op) {
        case SX1:
            *out = (long long)(int8_t)value;
            return true;
        case SX2:
            *out = (long long)(int16_t)value;
            return true;
        case SX4:
            *out = (long long)(int32_t)value;
            return true;
        case ZX1:
            *out = (long long)(uint8_t)value;
            return true;
        case ZX2:
            *out = (long long)(uint16_t)value;
            return true;
        case ZX4:
            *out = (long long)(uint32_t)value;
            return true;
        default:
            return false;
    }
}

static void emit_mov_nop(CCCC *vm, CCCCPc pc) {
    vm->text_seg[pc + 0] = MOV3;
    vm->text_seg[pc + 1] = ENCODE_RR(REG_ZERO, REG_ZERO);
}

static void emit_li_nop(CCCC *vm, CCCCPc pc) {
    vm->text_seg[pc + 0] = LI3;
    vm->text_seg[pc + 1] = ENCODE_R(REG_ZERO);
    cc_write_i64_at(vm, pc + 2, 0);
}



// Volatile semantics note: all three optimization passes below are safe for
// volatile-qualified accesses. Memory loads always call invalidate_reg() so
// their results are never constant-folded; stores are never removed by the
// DCE pass; and the peephole pass only combines sign/zero-extension ops with
// loads, which preserves the underlying memory access.
static void opt_constant_fold(CCCC *vm, OptReplacement *repls) {
    if (!vm || !vm->text_seg || !vm->text_ptr) {
        return;
    }

    RegState state;
    reset_reg_state(&state);

    CCCCPc start = 1;  // Skip entry point at text_seg[0]
    CCCCPc end = vm->text_ptr + 1;
    CCCCPc pc = start;

    int folded_count = 0;
    bool *control_flow_targets = build_control_flow_targets(vm, start, end);

    while (pc < end) {
        if (pc != start && control_flow_targets[pc - start])
            reset_reg_state(&state);

        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);
        if (size <= 0)
            break;

        switch (op) {
            case LI3: {
                // LI3 rd, imm - register gets constant value
                int rd = vm->text_seg[pc + 1] & 0xFF;
                long long imm = cc_read_i64_at(vm, pc + 2);
                set_const_reg(&state, rd, imm);
                break;
            }

            case ADD3:
            case ADDC:
            case SUB3:
            case SUBC:
            case MUL3:
            case MULC:
            case DIV3:
            case DIVC:
            case UDIV3:
            case MOD3:
            case UMOD3:
            case AND3:
            case OR3:
            case XOR3:
            case SHL3:
            case SHR3:
            case USHR3:
            case SEQ3:
            case SNE3:
            case SLT3:
            case SGE3:
            case SGT3:
            case SLE3: {
                // OP3 rd, rs1, rs2 - check if both operands are constants
                int rd, rs1, rs2;
                DECODE_RRR(vm->text_seg[pc + 1], rd, rs1, rs2);

                if (rs1 < MAX_TRACKED_REGS && rs2 < MAX_TRACKED_REGS &&
                    state.is_const[rs1] && state.is_const[rs2] &&
                    rd != 0) {

                    long long a = state.value[rs1];
                    long long b = state.value[rs2];
                    long long result = 0;
                    bool can_fold = eval_binary_const(
                        op, a, b, vm->flags & CCCC_OVERFLOW_CHECKS, &result);

                    if (can_fold) {
                        set_li_replacement(repls, pc, rd, result);
                        folded_count++;
                        set_const_reg(&state, rd, result);
                    }
                } else {
                    // Result is not a constant
                    invalidate_reg(&state, rd);
                }
                break;
            }

            case MOV3: {
                // MOV3 rd, rs - copy constant status
                int rd = vm->text_seg[pc + 1] & 0xFF;
                int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
                if (rs < MAX_TRACKED_REGS && state.is_const[rs])
                    set_const_reg(&state, rd, state.value[rs]);
                else
                    invalidate_reg(&state, rd);
                break;
            }

            case NEG3:
            case NOT3:
            case BNOT3: {
                // Unary ops: rd = OP(rs)
                int rd = vm->text_seg[pc + 1] & 0xFF;
                int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
                if (rd < MAX_TRACKED_REGS && rd != 0 &&
                    rs < MAX_TRACKED_REGS && state.is_const[rs]) {
                    long long result = 0;
                    if (eval_unary_const(op, state.value[rs], &result)) {
                        set_li_replacement(repls, pc, rd, result);
                        folded_count++;
                        set_const_reg(&state, rd, result);
                    }
                } else {
                    invalidate_reg(&state, rd);
                }
                break;
            }

            case ADDI3: {
                // ADDI3 rd, rs, imm - if rs is const, result is const
                int rd = vm->text_seg[pc + 1] & 0xFF;
                int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
                long long imm = cc_read_i64_at(vm, pc + 2);
                if (rd < MAX_TRACKED_REGS && rd != 0 &&
                    rs < MAX_TRACKED_REGS && state.is_const[rs]) {
                    long long result = 0;
                    if (eval_binary_const(ADD3, state.value[rs], imm,
                                          vm->flags & CCCC_OVERFLOW_CHECKS,
                                          &result)) {
                        vm->text_seg[pc + 0] = LI3;
                        vm->text_seg[pc + 1] = ENCODE_R(rd);
                        cc_write_i64_at(vm, pc + 2, result);
                        set_const_reg(&state, rd, result);
                        folded_count++;
                    }
                } else {
                    invalidate_reg(&state, rd);
                }
                break;
            }

            case SX1:
            case SX2:
            case SX4:
            case ZX1:
            case ZX2:
            case ZX4: {
                int rd = vm->text_seg[pc + 1] & 0xFF;
                int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
                if (rd < MAX_TRACKED_REGS && rd != 0 &&
                    rs < MAX_TRACKED_REGS && state.is_const[rs]) {
                    long long result = 0;
                    if (eval_extend_const(op, state.value[rs], &result)) {
                        set_li_replacement(repls, pc, rd, result);
                        folded_count++;
                        set_const_reg(&state, rd, result);
                    }
                } else {
                    invalidate_reg(&state, rd);
                }
                break;
            }

            case LDA3:
            case LTA3:
            case LEA3: {
                int rd = vm->text_seg[pc + 1] & 0xFF;
                invalidate_reg(&state, rd);
                break;
            }

            // Control flow - invalidate all tracked constants
            case JMP:
            case JZ3:
            case JNZ3:
            case JMPT:
            case JMPI:
            case CALL:
            case CALLT:
            case CALLI:
            case CALLN:
            case ENT3:
            case LEV3:
                reset_reg_state(&state);
                break;

            // Loads from memory - result is not constant
            case LDR_B:
            case LDR_H:
            case LDR_W:
            case LDR_D:
            case FLDR:
            case LDR_LOCAL_B:
            case LDR_LOCAL_H:
            case LDR_LOCAL_W:
            case LDR_LOCAL_D:
            case FLDR_LOCAL:
            case FLDR_LOCAL_F32:
            case LDR_INDEX_B:
            case LDR_INDEX_H:
            case LDR_INDEX_W:
            case LDR_INDEX_D:
            case FLDR_INDEX:
            case FLDR_INDEX_F32: {
                int rd = vm->text_seg[pc + 1] & 0xFF;
                invalidate_reg(&state, rd);
                break;
            }

            // Function calls clobber return registers
            case CALLF:
                invalidate_reg(&state, REG_A0);
                break;

            default:
                if (size == 2)
                    invalidate_reg(&state, vm->text_seg[pc + 1] & 0xFF);
                break;
        }

        pc += size;
    }

    if (vm->debug_vm && folded_count > 0) {
        printf("[opt] constant folding: rewrote %d constant expressions\n", folded_count);
    }

    free(control_flow_targets);
}

// ========== Pass 2: Peephole Optimization ==========
//
// Pattern match and remove redundant instruction sequences.
// Uses a sliding window approach with pattern matching.
//
// Patterns:
// 1. MOV3/FMOV3 ra, ra -> NOP (self-move)
// 2. LI3 rx, A; LI3 rx, B -> LI3 rx, B (overwritten load)
// 3. PSH3 rx; POP3 rx -> NOP (push/pop same register)
// 4. JMP to next instruction -> NOP
// 5. LDR_W rd, rs; SX4 rd, rd -> LDR_W rd, rs (SX4 is redundant)
//

static void opt_peephole(CCCC *vm) {
    if (!vm || !vm->text_seg || !vm->text_ptr) {
        return;
    }

    CCCCPc start = 1;  // Skip entry point
    CCCCPc end = vm->text_ptr + 1;
    int opt_count = 0;
    bool *control_flow_targets = build_control_flow_targets(vm, start, end);

    // Pattern 1: MOV3/FMOV3 ra, ra -> NOP (self-move)
    for (CCCCPc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);

        if (op == MOV3 || op == FMOV3) {
            int rd = vm->text_seg[pc + 1] & 0xFF;
            int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
            if (rd == rs && rd != 0) {
                // Self-move - convert to NOP
                emit_mov_nop(vm, pc);
                opt_count++;
            }
        }
        pc += size;
    }

    // Pattern 2: LI3 rx, A; LI3 rx, B -> NOP; LI3 rx, B
    for (CCCCPc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);

        if (op == LI3 && pc + size < end) {
            CCCCPc next = pc + size;
            int next_op = get_opcode(vm, next);
            if (next_op == LI3 && !control_flow_targets[next - start]) {
                int rd1 = vm->text_seg[pc + 1] & 0xFF;
                int rd2 = vm->text_seg[next + 1] & 0xFF;
                if (rd1 == rd2 && rd1 != REG_ZERO) {
                    emit_li_nop(vm, pc);
                    opt_count++;
                }
            }
        }
        pc += size;
    }

    // Pattern 3: PSH3 rx; POP3 rx -> NOP; NOP (useless push/pop)
    for (CCCCPc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);

        if (op == PSH3 && pc + size < end) {
            CCCCPc next = pc + size;
            int next_op = get_opcode(vm, next);
            if (next_op == POP3) {
                int rs_push = vm->text_seg[pc + 1] & 0xFF;
                int rd_pop = vm->text_seg[next + 1] & 0xFF;
                if (rs_push == rd_pop) {
                    // Push then pop same register - useless
                    emit_mov_nop(vm, pc);
                    emit_mov_nop(vm, next);
                    opt_count++;
                }
            }
        }
        pc += size;
    }

    // Pattern 4: JMP to next instruction -> NOP
    for (CCCCPc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);

        if (op == JMP) {
            long long target = vm->text_seg[pc + 1];
            CCCCPc next = pc + size;
            if (!control_flow_targets[pc - start] &&
                target == (long long)next) {
                // Jump to the very next instruction - useless
                emit_mov_nop(vm, pc);
                opt_count++;
            }
        }
        pc += size;
    }

    // Pattern 5: LDR_W rd, rs; SX4 rd, rd -> LDR_W rd, rs (SX4 is redundant)
    // LDR_W already sign-extends to 64 bits, so a self-extending SX4 on the same register is a no-op.
    // Do NOT apply to ZX4 — unsigned loads need the zero-extension.
    for (CCCCPc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);

        if (op == LDR_W && pc + size < end) {
            CCCCPc next = pc + size;
            if (!control_flow_targets[next - start]) {
                int next_op = get_opcode(vm, next);
                if (next_op == SX4) {
                    int rd_ldr = vm->text_seg[pc   + 1] & 0xFF;
                    int rd_sx4 = vm->text_seg[next + 1] & 0xFF;
                    int rs_sx4 = (vm->text_seg[next + 1] >> 8) & 0xFF;
                    if (rd_ldr == rd_sx4 && rd_sx4 == rs_sx4) {
                        emit_mov_nop(vm, next);
                        opt_count++;
                    }
                }
            }
        }
        pc += size;
    }

    if (vm->debug_vm && opt_count > 0) {
        printf("[opt] peephole: removed %d redundant instructions\n", opt_count);
    }

    free(control_flow_targets);
}

// ========== Pass 3: Dead Code Elimination ==========
//
// Remove clearly unreachable code - conservative approach.
// Only remove code that is demonstrably dead without complex analysis.
//
// Current implementation: Just count NOP sequences from previous passes.
// Actual code removal requires careful jump target tracking which is complex.
//
// Safe patterns we can detect:
// 1. Consecutive identical LI3 to same reg (second overwrites first)
// 2. Store followed immediately by another store to same address
//

static void opt_dead_code(CCCC *vm) {
    if (!vm || !vm->text_seg || !vm->text_ptr) {
        return;
    }

    CCCCPc start = 1;  // Skip entry point
    CCCCPc end = vm->text_ptr + 1;
    int dce_count = 0;

    // Count NOPs created by previous passes (informational only)
    int nop_count = 0;
    for (CCCCPc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);

        // Check if this is a NOP
        if (op == MOV3) {
            int rd = vm->text_seg[pc + 1] & 0xFF;
            int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
            if (rd == 0 && rs == 0) nop_count++;
        } else if (op == LI3) {
            int rd = vm->text_seg[pc + 1] & 0xFF;
            if (rd == 0 && cc_read_i64_at(vm, pc + 2) == 0) nop_count++;
        }
        pc += size;
    }

    // Pattern: MOV3 rd, rs followed by another MOV3 rd, rx -> first is dead
    // (if rd is overwritten before being read)
    for (CCCCPc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);

        if (op == MOV3 && pc + size < end) {
            int rd1 = vm->text_seg[pc + 1] & 0xFF;
            CCCCPc next = pc + size;
            int next_op = get_opcode(vm, next);

            if (next_op == MOV3) {
                int rd2 = vm->text_seg[next + 1] & 0xFF;
                if (rd1 == rd2 && rd1 != 0) {
                    // Consecutive MOV3 to same register - first is dead
                    emit_mov_nop(vm, pc);
                    dce_count++;
                }
            }
        }
        pc += size;
    }

    if (vm->debug_vm && (dce_count > 0 || nop_count > 0)) {
        printf("[opt] dead code: %d instructions removed, %d NOPs present\n",
               dce_count, nop_count);
    }
}

// ========== Pass 4: Bytecode Compaction ==========

static void retarget_compacted_bytecode(CCCC *vm, CCCCPc *pc_map,
                                        CCCCPc *new_to_old,
                                        CCCCPc old_end,
                                        CCCCPc new_end) {
    vm->text_seg[0] = remap_pc(pc_map, old_end, vm->text_seg[0]);

    for (CCCCPc pc = 1; pc < new_end; ) {
        CCCCPc old_pc = new_to_old[pc];
        int op = get_opcode(vm, pc);
        int size = get_compacted_instr_size_at(vm, pc, new_end);
        if (size <= 0)
            break;

        if (op == JMP || op == CALL) {
            CCCCPc old_target = vm->text_seg[pc + 1];
            vm->text_seg[pc + 1] = remap_pc(pc_map, old_end, old_target);
        } else if (op == JZ3 || op == JNZ3) {
            CCCCPc old_target = vm->text_seg[pc + 2];
            vm->text_seg[pc + 2] = remap_pc(pc_map, old_end, old_target);
        } else if (op == JMPT && pc + 3 < new_end && old_pc <= old_end) {
            CCCCPc old_table = vm->text_seg[pc + 1];
            CCCCInstrWord count = vm->text_seg[pc + 2];
            CCCCPc old_default = vm->text_seg[pc + 3];
            CCCCPc new_table = remap_pc(pc_map, old_end, old_table);
            vm->text_seg[pc + 1] = new_table;
            vm->text_seg[pc + 3] = remap_pc(pc_map, old_end, old_default);
            if (new_table + (CCCCPc)count <= new_end) {
                for (CCCCInstrWord i = 0; i < count; i++) {
                    CCCCPc entry = new_table + (CCCCPc)i;
                    vm->text_seg[entry] =
                        remap_pc(pc_map, old_end, vm->text_seg[entry]);
                }
            }
        } else if (op == LTA3) {
            remap_text_byte_offset_at(vm, pc + 2, pc_map, old_end);
        }

        pc += size;
    }

    remap_function_metadata(vm->compiler.globals, pc_map, old_end);

    if (vm->dbg.source_map) {
        for (int i = 0; i < vm->dbg.source_map_count; i++) {
            long long pc = vm->dbg.source_map[i].pc_offset;
            if (pc >= 0 && (CCCCPc)pc <= old_end)
                vm->dbg.source_map[i].pc_offset =
                    remap_pc(pc_map, old_end, (CCCCPc)pc);
        }
    }

    for (int i = 0; i < vm->compiler.num_data_relocs; i++) {
        if (vm->compiler.data_relocs[i].target_segment != 1)
            continue;
        CCCCPc old_pc = cc_byte_offset_to_pc(
            vm->compiler.data_relocs[i].target_offset);
        if (old_pc == CCCC_INVALID_PC || old_pc > old_end)
            continue;
        CCCCPc new_pc = remap_pc(pc_map, old_end, old_pc);
        long long new_offset = cc_pc_to_byte_offset(new_pc);
        vm->compiler.data_relocs[i].target_offset = new_offset;
        long long value = new_offset + vm->compiler.data_relocs[i].addend;
        *(long long *)(vm->data_seg +
                       vm->compiler.data_relocs[i].data_offset) = value;
    }
}

static void opt_compact_bytecode(CCCC *vm, OptReplacement *repls) {
    if (!vm || !vm->text_seg || !vm->text_ptr)
        return;

    CCCCPc old_end = vm->text_ptr + 1;
    CCCCPc *pc_map = calloc((size_t)old_end + 1, sizeof(CCCCPc));
    CCCCPc *new_to_old = calloc((size_t)old_end + 8, sizeof(CCCCPc));
    if (!pc_map || !new_to_old)
        error("out of memory");

    CCCCInstrWord *new_text = malloc(((size_t)old_end + 8) *
                                    sizeof(CCCCInstrWord));
    if (!new_text)
        error("out of memory");

    size_t cap = (size_t)old_end + 8;
    CCCCPc out = 1;
    new_text[0] = vm->text_seg[0];
    new_to_old[0] = 0;

    int removed = 0;
    int expanded = 0;

    for (CCCCPc pc = 1; pc < old_end; ) {
        int op = get_opcode(vm, pc);
        int old_size = get_instr_size_at(vm, pc, old_end);
        if (old_size <= 0)
            break;

        CCCCPc next = pc + (CCCCPc)old_size;
        bool remove = !repls[pc].active && is_nop_at(vm, pc);
        if (!remove && !repls[pc].active && next < old_end)
            remove = li_matches_replacement(vm, pc, &repls[next]);
        int new_size = remove ? 0 : (repls[pc].active ? repls[pc].nwords
                                                       : old_size);
        pc_map[pc] = out;
        for (int i = 1; i < old_size && pc + (CCCCPc)i <= old_end; i++)
            pc_map[pc + (CCCCPc)i] = out;
        if (op == JMPT && pc + 3 < old_end) {
            CCCCPc table_pc = vm->text_seg[pc + 1];
            CCCCInstrWord count = vm->text_seg[pc + 2];
            if (table_pc == pc + 4 &&
                table_pc + (CCCCPc)count <= old_end) {
                for (CCCCInstrWord i = 0; i < count; i++)
                    pc_map[table_pc + (CCCCPc)i] =
                        out + 4 + (CCCCPc)i;
            }
        }

        if (remove) {
            removed++;
            pc += old_size;
            continue;
        }

        if ((size_t)out + (size_t)new_size + 1 > cap) {
            cap = (cap * 2) + (size_t)new_size + 8;
            CCCCInstrWord *grown =
                realloc(new_text, cap * sizeof(CCCCInstrWord));
            CCCCPc *grown_old = realloc(new_to_old, cap * sizeof(CCCCPc));
            if (!grown || !grown_old)
                error("out of memory");
            new_text = grown;
            new_to_old = grown_old;
        }

        if (repls[pc].active) {
            memcpy(&new_text[out], repls[pc].words,
                   (size_t)new_size * sizeof(CCCCInstrWord));
            if (new_size != old_size)
                expanded++;
        } else {
            memcpy(&new_text[out], &vm->text_seg[pc],
                   (size_t)old_size * sizeof(CCCCInstrWord));
        }
        for (int i = 0; i < new_size; i++)
            new_to_old[out + (CCCCPc)i] = pc;

        out += (CCCCPc)new_size;
        pc += old_size;
    }
    pc_map[old_end] = out;

    if (out != old_end || removed > 0 || expanded > 0) {
        if (vm_text_ensure_count(vm, out + 1) != 0)
            error("optimizer: text segment overflow during compaction");
        memcpy(&vm->text_seg[1], &new_text[1],
               ((size_t)out - 1) * sizeof(CCCCInstrWord));
        vm->text_ptr = out - 1;
        retarget_compacted_bytecode(vm, pc_map, new_to_old, old_end, out);
        if (vm->debug_vm) {
            printf("[opt] compaction: removed %d NOPs, expanded %d folds, "
                   "text words %u -> %u\n",
                   removed, expanded, old_end, out);
        }
    }

    free(new_text);
    free(new_to_old);
    free(pc_map);
}

// ========== Main Entry Point ==========

void cc_optimize(CCCC *vm, int level) {
    if (!vm || !vm->text_seg || level <= 0) {
        return;
    }

    CCCCPc end = vm->text_ptr + 1;
    OptReplacement *repls = calloc((size_t)end + 1, sizeof(OptReplacement));
    if (!repls)
        error("out of memory");

    // Level 1: Basic optimization (constant folding)
    if (level >= 1) {
        opt_constant_fold(vm, repls);
    }

    // Level 2: Standard optimization (+ peephole)
    if (level >= 2) {
        opt_peephole(vm);
    }

    // Level 3: Aggressive optimization (+ dead code elimination)
    if (level >= 3) {
        opt_dead_code(vm);
    }

    opt_compact_bytecode(vm, repls);
    free(repls);
}
