/*
 JCC: JIT C Compiler

 Copyright (C) 2025 George Watson

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#include "jcc.h"
#include "./internal.h"
#include <limits.h>

//
// Bytecode Optimizer
//
// This module implements optional optimization passes on the generated bytecode.
// The optimizer runs after codegen and before execution, operating on the
// text_seg[] array of instructions.
//
// Optimization Levels:
//   -O0: No optimization (default)
//   -O1: Basic - constant folding
//   -O2: Standard - constant folding + peephole
//   -O3: Aggressive - all passes including dead code elimination
//

// ========== Helper Functions ==========

// Get opcode from instruction at pc
static int get_opcode(JCC *vm, JCCPc pc) {
    return (int)vm->text_seg[pc];
}

static int get_instr_size(int op) {
    return cc_instr_words(op);
}

static void mark_text_target(JCC *vm, bool *targets, JCCPc start,
                             JCCPc end, JCCPc target) {
    (void)vm;
    if (target >= start && target < end)
        targets[target - start] = true;
}

static bool *build_control_flow_targets(JCC *vm, JCCPc start,
                                        JCCPc end) {
    size_t count = (size_t)(end - start + 1);
    bool *targets = calloc(count, sizeof(bool));
    if (!targets)
        error("out of memory");

    for (JCCPc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size(op);
        if (size <= 0)
            break;

        if (op == JMP || op == CALL) {
            mark_text_target(vm, targets, start, end, vm->text_seg[pc + 1]);
        } else if (op == JZ3 || op == JNZ3) {
            mark_text_target(vm, targets, start, end, vm->text_seg[pc + 2]);
        } else if (op == LTA3) {
            JCCPc target = cc_byte_offset_to_pc(cc_read_i64_at(vm, pc + 2));
            mark_text_target(vm, targets, start, end, target);
        }

        pc += size;
    }

    return targets;
}

// ========== Pass 1: Constant Folding ==========
//
// Fold arithmetic operations on constant values at compile time.
// Pattern: LI3 rx, A; LI3 ry, B; OP3 rz, rx, ry -> LI3 rz, (A OP B)
//
// We use a simple value tracking approach:
// - Track which registers hold known constant values
// - When we see an arithmetic op with two constant operands, fold it
// - Replace the instruction sequence with a single LI3
//

// Maximum registers to track
#define MAX_TRACKED_REGS 32

// Track constant values in registers
typedef struct {
    bool is_const[MAX_TRACKED_REGS];
    long long value[MAX_TRACKED_REGS];
} RegState;

// Reset register state (e.g., at function boundaries, jumps)
static void reset_reg_state(RegState *state) {
    for (int i = 0; i < MAX_TRACKED_REGS; i++) {
        state->is_const[i] = false;
        state->value[i] = 0;
    }
    state->is_const[REG_ZERO] = true;
    state->value[REG_ZERO] = 0;
}

static void set_const_reg(RegState *state, int rd, long long value) {
    if (rd <= REG_ZERO || rd >= MAX_TRACKED_REGS)
        return;
    state->is_const[rd] = true;
    state->value[rd] = value;
}

static void invalidate_reg(RegState *state, int rd) {
    if (rd <= REG_ZERO || rd >= MAX_TRACKED_REGS)
        return;
    state->is_const[rd] = false;
    state->value[rd] = 0;
}

static int find_const_reg(RegState *state, long long value) {
    for (int i = 0; i < MAX_TRACKED_REGS; i++) {
        if (state->is_const[i] && state->value[i] == value)
            return i;
    }
    return -1;
}

static bool add_overflows(long long a, long long b) {
    return (b > 0 && a > LLONG_MAX - b) ||
           (b < 0 && a < LLONG_MIN - b);
}

static bool sub_overflows(long long a, long long b) {
    return (b < 0 && a > LLONG_MAX + b) ||
           (b > 0 && a < LLONG_MIN + b);
}

static bool mul_overflows(long long a, long long b) {
#if defined(__has_builtin)
#if __has_builtin(__builtin_mul_overflow)
    long long result;
    return __builtin_mul_overflow(a, b, &result);
#endif
#endif
    if (a > 0) {
        if (b > 0)
            return a > LLONG_MAX / b;
        return b < LLONG_MIN / a;
    }
    if (a < 0) {
        if (b > 0)
            return a < LLONG_MIN / b;
        return a != 0 && b < LLONG_MAX / a;
    }
    return false;
}

static bool eval_binary_const(int op, long long a, long long b,
                              bool preserve_overflow_traps,
                              long long *out) {
    switch (op) {
        case ADD3:
            if (preserve_overflow_traps && add_overflows(a, b))
                return false;
            *out = (long long)((unsigned long long)a + (unsigned long long)b);
            return true;
        case SUB3:
            if (preserve_overflow_traps && sub_overflows(a, b))
                return false;
            *out = (long long)((unsigned long long)a - (unsigned long long)b);
            return true;
        case MUL3:
            if (preserve_overflow_traps && mul_overflows(a, b))
                return false;
            *out = (long long)((unsigned long long)a * (unsigned long long)b);
            return true;
        case DIV3:
            if (b == 0 || (a == LLONG_MIN && b == -1))
                return false;
            *out = a / b;
            return true;
        case UDIV3:
            if (b == 0)
                return false;
            *out = (long long)((unsigned long long)a / (unsigned long long)b);
            return true;
        case MOD3:
            if (b == 0 || (a == LLONG_MIN && b == -1))
                return false;
            *out = a % b;
            return true;
        case UMOD3:
            if (b == 0)
                return false;
            *out = (long long)((unsigned long long)a % (unsigned long long)b);
            return true;
        case AND3:
            *out = a & b;
            return true;
        case OR3:
            *out = a | b;
            return true;
        case XOR3:
            *out = a ^ b;
            return true;
        case SHL3:
            if (b < 0 || b >= 63 || a < 0 || a > (LLONG_MAX >> b))
                return false;
            *out = a << b;
            return true;
        case SHR3:
            if (b < 0 || b >= 64 || a < 0)
                return false;
            *out = a >> b;
            return true;
        case USHR3:
            if (b < 0 || b >= 64)
                return false;
            *out = (long long)((unsigned long long)a >> b);
            return true;
        case SEQ3:
            *out = (a == b) ? 1 : 0;
            return true;
        case SNE3:
            *out = (a != b) ? 1 : 0;
            return true;
        case SLT3:
            *out = (a < b) ? 1 : 0;
            return true;
        case SGE3:
            *out = (a >= b) ? 1 : 0;
            return true;
        case SGT3:
            *out = (a > b) ? 1 : 0;
            return true;
        case SLE3:
            *out = (a <= b) ? 1 : 0;
            return true;
        default:
            return false;
    }
}

static bool eval_unary_const(int op, long long value, long long *out) {
    switch (op) {
        case NEG3:
            if (value == LLONG_MIN)
                return false;
            *out = -value;
            return true;
        case NOT3:
            *out = !value;
            return true;
        case BNOT3:
            *out = ~value;
            return true;
        default:
            return false;
    }
}

static bool eval_extend_const(int op, long long value, long long *out) {
    switch (op) {
        case SX1:
            *out = (long long)(int8_t)value;
            return true;
        case SX2:
            *out = (long long)(int16_t)value;
            return true;
        case SX4:
            *out = (long long)(int32_t)value;
            return true;
        case ZX1:
            *out = (long long)(uint8_t)value;
            return true;
        case ZX2:
            *out = (long long)(uint16_t)value;
            return true;
        case ZX4:
            *out = (long long)(uint32_t)value;
            return true;
        default:
            return false;
    }
}

static void emit_mov_nop(JCC *vm, JCCPc pc) {
    vm->text_seg[pc + 0] = MOV3;
    vm->text_seg[pc + 1] = ENCODE_RR(REG_ZERO, REG_ZERO);
}

static void emit_li_nop(JCC *vm, JCCPc pc) {
    vm->text_seg[pc + 0] = LI3;
    vm->text_seg[pc + 1] = ENCODE_R(REG_ZERO);
    cc_write_i64_at(vm, pc + 2, 0);
}



static void opt_constant_fold(JCC *vm) {
    if (!vm || !vm->text_seg || !vm->text_ptr) {
        return;
    }

    RegState state;
    reset_reg_state(&state);

    JCCPc start = 1;  // Skip entry point at text_seg[0]
    JCCPc end = vm->text_ptr + 1;
    JCCPc pc = start;

    int folded_count = 0;
    bool *control_flow_targets = build_control_flow_targets(vm, start, end);

    while (pc < end) {
        if (pc != start && control_flow_targets[pc - start])
            reset_reg_state(&state);

        int op = get_opcode(vm, pc);
        int size = get_instr_size(op);
        if (size <= 0)
            break;

        switch (op) {
            case LI3: {
                // LI3 rd, imm - register gets constant value
                int rd = vm->text_seg[pc + 1] & 0xFF;
                long long imm = cc_read_i64_at(vm, pc + 2);
                set_const_reg(&state, rd, imm);
                break;
            }

            case ADD3:
            case SUB3:
            case MUL3:
            case DIV3:
            case UDIV3:
            case MOD3:
            case UMOD3:
            case AND3:
            case OR3:
            case XOR3:
            case SHL3:
            case SHR3:
            case USHR3:
            case SEQ3:
            case SNE3:
            case SLT3:
            case SGE3:
            case SGT3:
            case SLE3: {
                // OP3 rd, rs1, rs2 - check if both operands are constants
                int rd, rs1, rs2;
                DECODE_RRR(vm->text_seg[pc + 1], rd, rs1, rs2);

                if (rs1 < MAX_TRACKED_REGS && rs2 < MAX_TRACKED_REGS &&
                    state.is_const[rs1] && state.is_const[rs2] &&
                    rd != 0) {
                    
                    long long a = state.value[rs1];
                    long long b = state.value[rs2];
                    long long result = 0;
                    bool can_fold = eval_binary_const(
                        op, a, b, vm->flags & JCC_OVERFLOW_CHECKS, &result);

                    if (can_fold) {
                        int const_reg = find_const_reg(&state, result);
                        if (const_reg >= 0) {
                            vm->text_seg[pc + 0] = MOV3;
                            vm->text_seg[pc + 1] = ENCODE_RR(rd, const_reg);
                            folded_count++;
                        }
                        set_const_reg(&state, rd, result);
                    }
                } else {
                    // Result is not a constant
                    invalidate_reg(&state, rd);
                }
                break;
            }

            case MOV3: {
                // MOV3 rd, rs - copy constant status
                int rd = vm->text_seg[pc + 1] & 0xFF;
                int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
                if (rs < MAX_TRACKED_REGS && state.is_const[rs])
                    set_const_reg(&state, rd, state.value[rs]);
                else
                    invalidate_reg(&state, rd);
                break;
            }

            case NEG3:
            case NOT3:
            case BNOT3: {
                // Unary ops: rd = OP(rs)
                int rd = vm->text_seg[pc + 1] & 0xFF;
                int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
                if (rd < MAX_TRACKED_REGS && rd != 0 &&
                    rs < MAX_TRACKED_REGS && state.is_const[rs]) {
                    long long result = 0;
                    if (eval_unary_const(op, state.value[rs], &result)) {
                        int const_reg = find_const_reg(&state, result);
                        if (const_reg >= 0) {
                            vm->text_seg[pc + 0] = MOV3;
                            vm->text_seg[pc + 1] = ENCODE_RR(rd, const_reg);
                            folded_count++;
                        }
                        set_const_reg(&state, rd, result);
                    }
                } else {
                    invalidate_reg(&state, rd);
                }
                break;
            }

            case ADDI3: {
                // ADDI3 rd, rs, imm - if rs is const, result is const
                int rd = vm->text_seg[pc + 1] & 0xFF;
                int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
                long long imm = cc_read_i64_at(vm, pc + 2);
                if (rd < MAX_TRACKED_REGS && rd != 0 &&
                    rs < MAX_TRACKED_REGS && state.is_const[rs]) {
                    long long result = 0;
                    if (eval_binary_const(ADD3, state.value[rs], imm,
                                          vm->flags & JCC_OVERFLOW_CHECKS,
                                          &result)) {
                        vm->text_seg[pc + 0] = LI3;
                        vm->text_seg[pc + 1] = ENCODE_R(rd);
                        cc_write_i64_at(vm, pc + 2, result);
                        set_const_reg(&state, rd, result);
                        folded_count++;
                    }
                } else {
                    invalidate_reg(&state, rd);
                }
                break;
            }

            case SX1:
            case SX2:
            case SX4:
            case ZX1:
            case ZX2:
            case ZX4: {
                int rd = vm->text_seg[pc + 1] & 0xFF;
                int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
                if (rd < MAX_TRACKED_REGS && rd != 0 &&
                    rs < MAX_TRACKED_REGS && state.is_const[rs]) {
                    long long result = 0;
                    if (eval_extend_const(op, state.value[rs], &result)) {
                        int const_reg = find_const_reg(&state, result);
                        if (const_reg >= 0) {
                            vm->text_seg[pc + 0] = MOV3;
                            vm->text_seg[pc + 1] = ENCODE_RR(rd, const_reg);
                            folded_count++;
                        }
                        set_const_reg(&state, rd, result);
                    }
                } else {
                    invalidate_reg(&state, rd);
                }
                break;
            }

            case LDA3:
            case LTA3:
            case LEA3: {
                int rd = vm->text_seg[pc + 1] & 0xFF;
                invalidate_reg(&state, rd);
                break;
            }

            // Control flow - invalidate all tracked constants
            case JMP:
            case JZ3:
            case JNZ3:
            case JMPT:
            case JMPI:
            case CALL:
            case CALLI:
            case ENT3:
            case LEV3:
                reset_reg_state(&state);
                break;

            // Loads from memory - result is not constant
            case LDR_B:
            case LDR_H:
            case LDR_W:
            case LDR_D:
            case FLDR: {
                int rd = vm->text_seg[pc + 1] & 0xFF;
                invalidate_reg(&state, rd);
                break;
            }

            // Function calls clobber return registers
            case CALLF:
                invalidate_reg(&state, REG_A0);
                break;

            default:
                if (size == 2)
                    invalidate_reg(&state, vm->text_seg[pc + 1] & 0xFF);
                break;
        }

        pc += size;
    }

    if (vm->debug_vm && folded_count > 0) {
        printf("[opt] constant folding: rewrote %d constant expressions\n", folded_count);
    }

    free(control_flow_targets);
}

// ========== Pass 2: Peephole Optimization ==========
//
// Pattern match and remove redundant instruction sequences.
// Uses a sliding window approach with pattern matching.
//
// Patterns:
// 1. MOV3/FMOV3 ra, ra -> NOP (self-move)
// 2. LI3 rx, A; LI3 rx, B -> LI3 rx, B (overwritten load)
// 3. PSH3 rx; POP3 rx -> NOP (push/pop same register)
// 4. JMP to next instruction -> NOP
//

static void opt_peephole(JCC *vm) {
    if (!vm || !vm->text_seg || !vm->text_ptr) {
        return;
    }

    JCCPc start = 1;  // Skip entry point
    JCCPc end = vm->text_ptr + 1;
    int opt_count = 0;
    bool *control_flow_targets = build_control_flow_targets(vm, start, end);

    // Pattern 1: MOV3/FMOV3 ra, ra -> NOP (self-move)
    for (JCCPc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size(op);

        if (op == MOV3 || op == FMOV3) {
            int rd = vm->text_seg[pc + 1] & 0xFF;
            int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
            if (rd == rs && rd != 0) {
                // Self-move - convert to NOP
                emit_mov_nop(vm, pc);
                opt_count++;
            }
        }
        pc += size;
    }

    // Pattern 2: LI3 rx, A; LI3 rx, B -> NOP; LI3 rx, B
    for (JCCPc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size(op);

        if (op == LI3 && pc + size < end) {
            JCCPc next = pc + size;
            int next_op = get_opcode(vm, next);
            if (next_op == LI3 && !control_flow_targets[next - start]) {
                int rd1 = vm->text_seg[pc + 1] & 0xFF;
                int rd2 = vm->text_seg[next + 1] & 0xFF;
                if (rd1 == rd2 && rd1 != REG_ZERO) {
                    emit_li_nop(vm, pc);
                    opt_count++;
                }
            }
        }
        pc += size;
    }

    // Pattern 3: PSH3 rx; POP3 rx -> NOP; NOP (useless push/pop)
    for (JCCPc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size(op);

        if (op == PSH3 && pc + size < end) {
            JCCPc next = pc + size;
            int next_op = get_opcode(vm, next);
            if (next_op == POP3) {
                int rs_push = vm->text_seg[pc + 1] & 0xFF;
                int rd_pop = vm->text_seg[next + 1] & 0xFF;
                if (rs_push == rd_pop) {
                    // Push then pop same register - useless
                    emit_mov_nop(vm, pc);
                    emit_mov_nop(vm, next);
                    opt_count++;
                }
            }
        }
        pc += size;
    }

    // Pattern 4: JMP to next instruction -> NOP
    for (JCCPc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size(op);

        if (op == JMP) {
            long long target = vm->text_seg[pc + 1];
            JCCPc next = pc + size;
            if (!control_flow_targets[pc - start] &&
                target == (long long)next) {
                // Jump to the very next instruction - useless
                emit_mov_nop(vm, pc);
                opt_count++;
            }
        }
        pc += size;
    }

    // Pattern 5: MOV3 ra, rb; MOV3 rb, ra -> MOV3 ra, rb (second is nop if rb not used)
    // This is more complex - skip for now

    if (vm->debug_vm && opt_count > 0) {
        printf("[opt] peephole: removed %d redundant instructions\n", opt_count);
    }

    free(control_flow_targets);
}

// ========== Pass 3: Dead Code Elimination ==========
//
// Remove clearly unreachable code - conservative approach.
// Only remove code that is demonstrably dead without complex analysis.
//
// Current implementation: Just count NOP sequences from previous passes.
// Actual code removal requires careful jump target tracking which is complex.
//
// Safe patterns we can detect:
// 1. Consecutive identical LI3 to same reg (second overwrites first)
// 2. Store followed immediately by another store to same address
//

static void opt_dead_code(JCC *vm) {
    if (!vm || !vm->text_seg || !vm->text_ptr) {
        return;
    }

    JCCPc start = 1;  // Skip entry point
    JCCPc end = vm->text_ptr + 1;
    int dce_count = 0;

    // Count NOPs created by previous passes (informational only)
    int nop_count = 0;
    for (JCCPc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size(op);

        // Check if this is a NOP
        if (op == MOV3) {
            int rd = vm->text_seg[pc + 1] & 0xFF;
            int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
            if (rd == 0 && rs == 0) nop_count++;
        } else if (op == LI3) {
            int rd = vm->text_seg[pc + 1] & 0xFF;
            if (rd == 0 && cc_read_i64_at(vm, pc + 2) == 0) nop_count++;
        }
        pc += size;
    }

    // Pattern: MOV3 rd, rs followed by another MOV3 rd, rx -> first is dead
    // (if rd is overwritten before being read)
    for (JCCPc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size(op);

        if (op == MOV3 && pc + size < end) {
            int rd1 = vm->text_seg[pc + 1] & 0xFF;
            JCCPc next = pc + size;
            int next_op = get_opcode(vm, next);
            
            if (next_op == MOV3) {
                int rd2 = vm->text_seg[next + 1] & 0xFF;
                if (rd1 == rd2 && rd1 != 0) {
                    // Consecutive MOV3 to same register - first is dead
                    emit_mov_nop(vm, pc);
                    dce_count++;
                }
            }
        }
        pc += size;
    }

    if (vm->debug_vm && (dce_count > 0 || nop_count > 0)) {
        printf("[opt] dead code: %d instructions removed, %d NOPs present\n", 
               dce_count, nop_count);
    }
}

// ========== Main Entry Point ==========

void cc_optimize(JCC *vm, int level) {
    if (!vm || !vm->text_seg || level <= 0) {
        return;
    }

    // Level 1: Basic optimization (constant folding)
    if (level >= 1) {
        opt_constant_fold(vm);
    }

    // Level 2: Standard optimization (+ peephole)
    if (level >= 2) {
        opt_peephole(vm);
    }

    // Level 3: Aggressive optimization (+ dead code elimination)
    if (level >= 3) {
        opt_dead_code(vm);
    }
}
