/*
 CCCC: Comprehensiev C Compensation Compiler

 Copyright (C) 2025 George Watson

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#include "./internal.h"


#define OPT_P_RS1 1
#define OPT_P_RS2 2
#define OPT_P_RS3 3

//
// Bytecode Optimizer
//
// This module implements optional optimization passes on the generated bytecode.
// The optimizer runs after codegen and before execution, operating on the
// text_seg[] array of instructions.
//
// Optimization Levels:
//   -O0: No optimization (default)
//   -O1: Basic - constant folding
//   -O2: Standard - constant folding + peephole
//   -O3: Aggressive - all passes including dead code elimination
//   -O4: Aggressive + automatic opcode fusion
//

// ========== Helper Functions ==========

// Get opcode from instruction at pc
static int get_opcode(VirtualMachine *vm, Pc pc) {
    return (int)vm->text_seg[pc];
}

static int get_instr_size(int op) {
    return cc_instr_words(op);
}

static int get_instr_size_at(VirtualMachine *vm, Pc pc, Pc end) {
    int op = get_opcode(vm, pc);
    int size = get_instr_size(op);
    if (op == JMPT && pc + 3 < end) {
        Pc table_pc = vm->text_seg[pc + 1];
        InstrWord count = vm->text_seg[pc + 2];
        if (table_pc == pc + 4 && table_pc + (Pc)count <= end)
            size += (int)count;
    }
    return size;
}

static int get_compacted_instr_size_at(VirtualMachine *vm, Pc pc, Pc end) {
    int op = get_opcode(vm, pc);
    int size = get_instr_size(op);
    if (op == JMPT && pc + 3 < end) {
        InstrWord count = vm->text_seg[pc + 2];
        if (pc + 4 + (Pc)count <= end)
            size += (int)count;
    }
    return size;
}

typedef struct {
    bool active;
    int nwords;
    InstrWord words[4];
} OptReplacement;

static void set_li_replacement(OptReplacement *repls, Pc pc, int rd,
                               long long imm) {
    repls[pc].active = true;
    repls[pc].nwords = 4;
    repls[pc].words[0] = LI3;
    repls[pc].words[1] = ENCODE_R(rd);
    repls[pc].words[2] = cc_i64_lo(imm);
    repls[pc].words[3] = cc_i64_hi(imm);
}

static void set_rri_replacement(OptReplacement *repls, Pc pc, int op, int rd,
                                int rs, long long imm) {
    repls[pc].active = true;
    repls[pc].nwords = 4;
    repls[pc].words[0] = (InstrWord)op;
    repls[pc].words[1] = ENCODE_RR(rd, rs);
    repls[pc].words[2] = cc_i64_lo(imm);
    repls[pc].words[3] = cc_i64_hi(imm);
}

static void set_rrri_replacement(OptReplacement *repls, Pc pc, int op, int rd,
                                 int rs1, int rs2, long long imm) {
    repls[pc].active = true;
    repls[pc].nwords = 4;
    repls[pc].words[0] = (InstrWord)op;
    repls[pc].words[1] = ENCODE_RRR(rd, rs1, rs2);
    repls[pc].words[2] = cc_i64_lo(imm);
    repls[pc].words[3] = cc_i64_hi(imm);
}

static void set_rrrr_replacement(OptReplacement *repls, Pc pc, int op, int rd,
                                 int rs1, int rs2, int rs3) {
    repls[pc].active = true;
    repls[pc].nwords = 2;
    repls[pc].words[0] = (InstrWord)op;
    repls[pc].words[1] = ENCODE_RRRR(rd, rs1, rs2, rs3);
}

static bool is_nop_at(VirtualMachine *vm, Pc pc) {
    int op = get_opcode(vm, pc);
    if (op == MOV3) {
        int rd = vm->text_seg[pc + 1] & 0xFF;
        int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
        return rd == REG_ZERO && rs == REG_ZERO;
    }
    if (op == LI3) {
        int rd = vm->text_seg[pc + 1] & 0xFF;
        return rd == REG_ZERO && cc_read_i64_at(vm, pc + 2) == 0;
    }
    return false;
}

static bool li_matches_replacement(VirtualMachine *vm, Pc pc,
                                   const OptReplacement *repl) {
    if (!repl->active || repl->nwords != 4 || repl->words[0] != LI3)
        return false;
    if (get_opcode(vm, pc) != LI3)
        return false;
    return vm->text_seg[pc + 1] == repl->words[1] &&
           vm->text_seg[pc + 2] == repl->words[2] &&
           vm->text_seg[pc + 3] == repl->words[3];
}

static Pc remap_pc(Pc *pc_map, Pc old_end, Pc target) {
    if (target == CCCC_INVALID_PC)
        return target;
    if (target <= old_end)
        return pc_map[target];
    return target;
}

static void remap_text_byte_offset_at(VirtualMachine *vm, Pc operand_pc,
                                      Pc *pc_map, Pc old_end) {
    long long old_offset = cc_read_i64_at(vm, operand_pc);
    Pc old_target = cc_byte_offset_to_pc(old_offset);
    if (old_target == CCCC_INVALID_PC)
        return;
    Pc new_target = remap_pc(pc_map, old_end, old_target);
    if (new_target != CCCC_INVALID_PC)
        cc_write_i64_at(vm, operand_pc, cc_pc_to_byte_offset(new_target));
}

static void remap_function_metadata(Obj *obj, Pc *pc_map, Pc old_end) {
    for (; obj; obj = obj->next) {
        if (obj->is_function) {
            if (obj->code_addr >= 0) {
                Pc pc = (Pc)obj->code_addr;
                if (pc <= old_end)
                    obj->code_addr = remap_pc(pc_map, old_end, pc);
            }
            if (obj->code_end_addr >= 0) {
                Pc pc = (Pc)obj->code_end_addr;
                if (pc <= old_end)
                    obj->code_end_addr = remap_pc(pc_map, old_end, pc);
            }
        }
    }
}

static void mark_text_target(VirtualMachine *vm, bool *targets, Pc start,
                             Pc end, Pc target) {
    (void)vm;
    if (target >= start && target < end)
        targets[target - start] = true;
}

static bool *build_control_flow_targets(VirtualMachine *vm, Pc start,
                                        Pc end) {
    size_t count = (size_t)(end - start + 1);
    bool *targets = calloc(count, sizeof(bool));
    if (!targets)
        error("out of memory");

    for (Pc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);
        if (size <= 0)
            break;

        if (op == JMP || op == CALL || op == CALLT) {
            mark_text_target(vm, targets, start, end, vm->text_seg[pc + 1]);
        } else if (op == JZ3 || op == JNZ3) {
            mark_text_target(vm, targets, start, end, vm->text_seg[pc + 2]);
        } else if (op == JMPT && pc + 3 < end) {
            Pc table_pc = vm->text_seg[pc + 1];
            InstrWord count = vm->text_seg[pc + 2];
            mark_text_target(vm, targets, start, end, vm->text_seg[pc + 3]);
            if (table_pc + (Pc)count <= end) {
                for (InstrWord i = 0; i < count; i++)
                    mark_text_target(vm, targets, start, end,
                                     vm->text_seg[table_pc + (Pc)i]);
            }
        } else if (op == LTA3) {
            Pc target = cc_byte_offset_to_pc(cc_read_i64_at(vm, pc + 2));
            mark_text_target(vm, targets, start, end, target);
        }

        pc += size;
    }

    return targets;
}

// ========== Pass 1: Constant Folding ==========
//
// Fold arithmetic operations on constant values at compile time.
// Pattern: LI3 rx, A; LI3 ry, B; OP3 rz, rx, ry -> LI3 rz, (A OP B)
//
// We use a simple value tracking approach:
// - Track which registers hold known constant values
// - When we see an arithmetic op with two constant operands, fold it
// - Replace the instruction sequence with a single LI3
//

// Maximum registers to track
#define MAX_TRACKED_REGS 32

// Track constant values in registers
typedef struct {
    bool is_const[MAX_TRACKED_REGS];
    long long value[MAX_TRACKED_REGS];
} RegState;

// Reset register state (e.g., at function boundaries, jumps)
static void reset_reg_state(RegState *state) {
    for (int i = 0; i < MAX_TRACKED_REGS; i++) {
        state->is_const[i] = false;
        state->value[i] = 0;
    }
    state->is_const[REG_ZERO] = true;
    state->value[REG_ZERO] = 0;
}

static void set_const_reg(RegState *state, int rd, long long value) {
    if (rd <= REG_ZERO || rd >= MAX_TRACKED_REGS)
        return;
    state->is_const[rd] = true;
    state->value[rd] = value;
}

static void invalidate_reg(RegState *state, int rd) {
    if (rd <= REG_ZERO || rd >= MAX_TRACKED_REGS)
        return;
    state->is_const[rd] = false;
    state->value[rd] = 0;
}

static bool add_overflows(long long a, long long b) {
    return (b > 0 && a > LLONG_MAX - b) ||
           (b < 0 && a < LLONG_MIN - b);
}

static bool sub_overflows(long long a, long long b) {
    return (b < 0 && a > LLONG_MAX + b) ||
           (b > 0 && a < LLONG_MIN + b);
}

static bool mul_overflows(long long a, long long b) {
#if defined(__has_builtin)
#if __has_builtin(__builtin_mul_overflow)
    long long result;
    return __builtin_mul_overflow(a, b, &result);
#endif
#endif
    if (a > 0) {
        if (b > 0)
            return a > LLONG_MAX / b;
        return b < LLONG_MIN / a;
    }
    if (a < 0) {
        if (b > 0)
            return a < LLONG_MIN / b;
        return a != 0 && b < LLONG_MAX / a;
    }
    return false;
}

static bool eval_binary_const(int op, long long a, long long b,
                              bool preserve_overflow_traps,
                              long long *out) {
    (void)preserve_overflow_traps;
    switch (op) {
        case ADD3:
            *out = (long long)((unsigned long long)a + (unsigned long long)b);
            return true;
        case ADDC:
            if (add_overflows(a, b))
                return false;
            *out = a + b;
            return true;
        case SUB3:
            *out = (long long)((unsigned long long)a - (unsigned long long)b);
            return true;
        case SUBC:
            if (sub_overflows(a, b))
                return false;
            *out = a - b;
            return true;
        case MUL3:
            *out = (long long)((unsigned long long)a * (unsigned long long)b);
            return true;
        case MULC:
            if (mul_overflows(a, b))
                return false;
            *out = a * b;
            return true;
        case DIV3:
            if (b == 0)
                return false;
            *out = (a == LLONG_MIN && b == -1) ? LLONG_MIN : a / b;
            return true;
        case DIVC:
            if (b == 0 || (a == LLONG_MIN && b == -1))
                return false;
            *out = a / b;
            return true;
        case UDIV3:
            if (b == 0)
                return false;
            *out = (long long)((unsigned long long)a / (unsigned long long)b);
            return true;
        case MOD3:
            if (b == 0 || (a == LLONG_MIN && b == -1))
                return false;
            *out = a % b;
            return true;
        case UMOD3:
            if (b == 0)
                return false;
            *out = (long long)((unsigned long long)a % (unsigned long long)b);
            return true;
        case AND3:
            *out = a & b;
            return true;
        case OR3:
            *out = a | b;
            return true;
        case XOR3:
            *out = a ^ b;
            return true;
        case SHL3:
            if (b < 0 || b >= 63 || a < 0 || a > (LLONG_MAX >> b))
                return false;
            *out = a << b;
            return true;
        case SHR3:
            if (b < 0 || b >= 64 || a < 0)
                return false;
            *out = a >> b;
            return true;
        case USHR3:
            if (b < 0 || b >= 64)
                return false;
            *out = (long long)((unsigned long long)a >> b);
            return true;
        case SEQ3:
            *out = (a == b) ? 1 : 0;
            return true;
        case SNE3:
            *out = (a != b) ? 1 : 0;
            return true;
        case SLT3:
            *out = (a < b) ? 1 : 0;
            return true;
        case SGE3:
            *out = (a >= b) ? 1 : 0;
            return true;
        case SGT3:
            *out = (a > b) ? 1 : 0;
            return true;
        case SLE3:
            *out = (a <= b) ? 1 : 0;
            return true;
        case ULT3:
            *out = ((unsigned long long)a < (unsigned long long)b) ? 1 : 0;
            return true;
        case ULE3:
            *out = ((unsigned long long)a <= (unsigned long long)b) ? 1 : 0;
            return true;
        default:
            return false;
    }
}

static bool eval_unary_const(int op, long long value, long long *out) {
    switch (op) {
        case NEG3:
            if (value == LLONG_MIN)
                return false;
            *out = -value;
            return true;
        case NOT3:
            *out = !value;
            return true;
        case BNOT3:
            *out = ~value;
            return true;
        default:
            return false;
    }
}

static bool eval_extend_const(int op, long long value, long long *out) {
    switch (op) {
        case SX1:
            *out = (long long)(int8_t)value;
            return true;
        case SX2:
            *out = (long long)(int16_t)value;
            return true;
        case SX4:
            *out = (long long)(int32_t)value;
            return true;
        case ZX1:
            *out = (long long)(uint8_t)value;
            return true;
        case ZX2:
            *out = (long long)(uint16_t)value;
            return true;
        case ZX4:
            *out = (long long)(uint32_t)value;
            return true;
        default:
            return false;
    }
}

static void emit_mov_nop(VirtualMachine *vm, Pc pc) {
    vm->text_seg[pc + 0] = MOV3;
    vm->text_seg[pc + 1] = ENCODE_RR(REG_ZERO, REG_ZERO);
}

static void emit_li_nop(VirtualMachine *vm, Pc pc) {
    vm->text_seg[pc + 0] = LI3;
    vm->text_seg[pc + 1] = ENCODE_R(REG_ZERO);
    cc_write_i64_at(vm, pc + 2, 0);
}



// Volatile semantics note: all three optimization passes below are safe for
// volatile-qualified accesses. Memory loads always call invalidate_reg() so
// their results are never constant-folded; stores are never removed by the
// DCE pass; and the peephole pass only combines sign/zero-extension ops with
// loads, which preserves the underlying memory access.
static void opt_constant_fold(VirtualMachine *vm, OptReplacement *repls,
                              Pc fn_start, Pc fn_end) {
    if (!vm || !vm->text_seg || !vm->text_ptr) {
        return;
    }

    RegState state;
    reset_reg_state(&state);

    Pc start = fn_start;
    Pc end = fn_end;
    Pc pc = start;

    int folded_count = 0;
    bool *control_flow_targets = build_control_flow_targets(vm, start, end);

    while (pc < end) {
        if (pc != start && control_flow_targets[pc - start])
            reset_reg_state(&state);

        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);
        if (size <= 0)
            break;

        switch (op) {
            case LI3: {
                // LI3 rd, imm - register gets constant value
                int rd = vm->text_seg[pc + 1] & 0xFF;
                long long imm = cc_read_i64_at(vm, pc + 2);
                set_const_reg(&state, rd, imm);
                break;
            }

            case ADD3:
            case ADDC:
            case SUB3:
            case SUBC:
            case MUL3:
            case MULC:
            case DIV3:
            case DIVC:
            case UDIV3:
            case MOD3:
            case UMOD3:
            case AND3:
            case OR3:
            case XOR3:
            case SHL3:
            case SHR3:
            case USHR3:
            case SEQ3:
            case SNE3:
            case SLT3:
            case SGE3:
            case SGT3:
            case SLE3:
            case ULT3:
            case ULE3: {
                // OP3 rd, rs1, rs2 - check if both operands are constants
                int rd, rs1, rs2;
                DECODE_RRR(vm->text_seg[pc + 1], rd, rs1, rs2);

                if (rs1 < MAX_TRACKED_REGS && rs2 < MAX_TRACKED_REGS &&
                    state.is_const[rs1] && state.is_const[rs2] &&
                    rd != 0) {

                    long long a = state.value[rs1];
                    long long b = state.value[rs2];
                    long long result = 0;
                    bool can_fold = eval_binary_const(
                        op, a, b, vm->flags & CCCC_OVERFLOW_CHECKS, &result);

                    if (can_fold) {
                        set_li_replacement(repls, pc, rd, result);
                        folded_count++;
                        set_const_reg(&state, rd, result);
                    } else {
                        // Operands are const but the op couldn't be folded
                        // (e.g. SHL3 overflow guard, division by zero) -
                        // rd's prior tracked value is now stale.
                        invalidate_reg(&state, rd);
                    }
                } else {
                    // Result is not a constant
                    invalidate_reg(&state, rd);
                }
                break;
            }

            case MOV3: {
                // MOV3 rd, rs - copy constant status
                int rd = vm->text_seg[pc + 1] & 0xFF;
                int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
                if (rs < MAX_TRACKED_REGS && state.is_const[rs])
                    set_const_reg(&state, rd, state.value[rs]);
                else
                    invalidate_reg(&state, rd);
                break;
            }

            case NEG3:
            case NOT3:
            case BNOT3: {
                // Unary ops: rd = OP(rs)
                int rd = vm->text_seg[pc + 1] & 0xFF;
                int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
                if (rd < MAX_TRACKED_REGS && rd != 0 &&
                    rs < MAX_TRACKED_REGS && state.is_const[rs]) {
                    long long result = 0;
                    if (eval_unary_const(op, state.value[rs], &result)) {
                        set_li_replacement(repls, pc, rd, result);
                        folded_count++;
                        set_const_reg(&state, rd, result);
                    }
                } else {
                    invalidate_reg(&state, rd);
                }
                break;
            }

            case ADDI3: {
                // ADDI3 rd, rs, imm - if rs is const, result is const
                int rd = vm->text_seg[pc + 1] & 0xFF;
                int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
                long long imm = cc_read_i64_at(vm, pc + 2);
                if (rd < MAX_TRACKED_REGS && rd != 0 &&
                    rs < MAX_TRACKED_REGS && state.is_const[rs]) {
                    long long result = 0;
                    if (eval_binary_const(ADD3, state.value[rs], imm,
                                          vm->flags & CCCC_OVERFLOW_CHECKS,
                                          &result)) {
                        vm->text_seg[pc + 0] = LI3;
                        vm->text_seg[pc + 1] = ENCODE_R(rd);
                        cc_write_i64_at(vm, pc + 2, result);
                        set_const_reg(&state, rd, result);
                        folded_count++;
                    }
                } else {
                    invalidate_reg(&state, rd);
                }
                break;
            }

            case SX1:
            case SX2:
            case SX4:
            case ZX1:
            case ZX2:
            case ZX4: {
                int rd = vm->text_seg[pc + 1] & 0xFF;
                int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
                if (rd < MAX_TRACKED_REGS && rd != 0 &&
                    rs < MAX_TRACKED_REGS && state.is_const[rs]) {
                    long long result = 0;
                    if (eval_extend_const(op, state.value[rs], &result)) {
                        set_li_replacement(repls, pc, rd, result);
                        folded_count++;
                        set_const_reg(&state, rd, result);
                    }
                } else {
                    invalidate_reg(&state, rd);
                }
                break;
            }

            case LDA3:
            case LTA3:
            case LEA3:
            // CLZ/CTZ/FFS/BSWAP are 3-word ops (rd|rs, bit/byte-width) that
            // write rd. They fall outside the `default` case's `size == 2`
            // check, so without an explicit case rd's prior constant value
            // was never invalidated.
            case CLZ:
            case CTZ:
            case FFS:
            case BSWAP: {
                int rd = vm->text_seg[pc + 1] & 0xFF;
                invalidate_reg(&state, rd);
                break;
            }

            // Control flow - invalidate all tracked constants
            case JMP:
            case JZ3:
            case JNZ3:
            case JMPT:
            case JMPI:
            case CALL:
            case CALLT:
            case CALLI:
            case CALLN:
            case ENT3:
            case LEV3:
                reset_reg_state(&state);
                break;

            // Loads from memory - result is not constant
            case LDR_B:
            case LDR_H:
            case LDR_W:
            case LDR_D:
            case FLDR:
            case LDR_LOCAL_B:
            case LDR_LOCAL_H:
            case LDR_LOCAL_W:
            case LDR_LOCAL_D:
            case FLDR_LOCAL:
            case FLDR_LOCAL_F32:
            case LDR_INDEX_B:
            case LDR_INDEX_H:
            case LDR_INDEX_W:
            case LDR_INDEX_D:
            case FLDR_INDEX:
            case FLDR_INDEX_F32: {
                int rd = vm->text_seg[pc + 1] & 0xFF;
                invalidate_reg(&state, rd);
                break;
            }

            // Function calls clobber return registers
            case CALLF:
            // Builtin ops that write their result into REG_A0 - any
            // previously tracked constant in REG_A0 (e.g. an argument
            // just loaded via LI3) is now stale.
            case CALC:
            case DLOPEN:
            case DLSYM:
            case DLCLOSE:
            case DLERROR:
            case IOVFL:
            case LONGJMP:
            case MALC:
            case REALC:
            case RETBUF:
            case SETJMP:
            case VRAISE:
            case VSIGNAL:
                invalidate_reg(&state, REG_A0);
                break;

            default:
                if (size == 2)
                    invalidate_reg(&state, vm->text_seg[pc + 1] & 0xFF);
                break;
        }

        pc += size;
    }

    if (vm->debug_vm && folded_count > 0) {
        printf("[opt] constant folding: rewrote %d constant expressions\n", folded_count);
    }

    free(control_flow_targets);
}

// ========== Pass 2: Peephole Optimization ==========
//
// Pattern match and remove redundant instruction sequences.
// Uses a sliding window approach with pattern matching.
//
// Patterns:
// 1. MOV3/FMOV3 ra, ra -> NOP (self-move)
// 2. LI3 rx, A; LI3 rx, B -> LI3 rx, B (overwritten load)
// 3. PSH3 rx; POP3 rx -> NOP (push/pop same register)
// 4. JMP to next instruction -> NOP
// 5. LDR_W rd, rs; SX4 rd, rd -> LDR_W rd, rs (SX4 is redundant)
//

// NOTE(#578): SX4/ZX4/ZX1 extension opcodes are ~20% of executed instructions
// (per --vm-profile on test_minilua). A redundant-extension elimination pass
// here — dropping extensions of already-in-range values — is a large win.
static void opt_peephole(VirtualMachine *vm, Pc fn_start, Pc fn_end) {
    if (!vm || !vm->text_seg || !vm->text_ptr) {
        return;
    }

    Pc start = fn_start;
    Pc end = fn_end;
    int opt_count = 0;
    bool *control_flow_targets = build_control_flow_targets(vm, start, end);

    // Pattern 1: MOV3/FMOV3 ra, ra -> NOP (self-move)
    for (Pc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);

        if (op == MOV3 || op == FMOV3) {
            int rd = vm->text_seg[pc + 1] & 0xFF;
            int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
            if (rd == rs && rd != 0) {
                // Self-move - convert to NOP
                emit_mov_nop(vm, pc);
                opt_count++;
            }
        }
        pc += size;
    }

    // Pattern 2: LI3 rx, A; LI3 rx, B -> NOP; LI3 rx, B
    for (Pc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);

        if (op == LI3 && pc + size < end) {
            Pc next = pc + size;
            int next_op = get_opcode(vm, next);
            if (next_op == LI3 && !control_flow_targets[next - start]) {
                int rd1 = vm->text_seg[pc + 1] & 0xFF;
                int rd2 = vm->text_seg[next + 1] & 0xFF;
                if (rd1 == rd2 && rd1 != REG_ZERO) {
                    emit_li_nop(vm, pc);
                    opt_count++;
                }
            }
        }
        pc += size;
    }

    // Pattern 3: PSH3 rx; POP3 rx -> NOP; NOP (useless push/pop)
    for (Pc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);

        if (op == PSH3 && pc + size < end) {
            Pc next = pc + size;
            int next_op = get_opcode(vm, next);
            if (next_op == POP3) {
                int rs_push = vm->text_seg[pc + 1] & 0xFF;
                int rd_pop = vm->text_seg[next + 1] & 0xFF;
                if (rs_push == rd_pop) {
                    // Push then pop same register - useless
                    emit_mov_nop(vm, pc);
                    emit_mov_nop(vm, next);
                    opt_count++;
                }
            }
        }
        pc += size;
    }

    // Pattern 4: JMP to next instruction -> NOP
    for (Pc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);

        if (op == JMP) {
            long long target = vm->text_seg[pc + 1];
            Pc next = pc + size;
            if (!control_flow_targets[pc - start] &&
                target == (long long)next) {
                // Jump to the very next instruction - useless
                emit_mov_nop(vm, pc);
                opt_count++;
            }
        }
        pc += size;
    }

    // Pattern 5: LDR_W rd, rs; SX4 rd, rd -> LDR_W rd, rs (SX4 is redundant)
    // LDR_W already sign-extends to 64 bits, so a self-extending SX4 on the same register is a no-op.
    // Do NOT apply to ZX4 — unsigned loads need the zero-extension.
    for (Pc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);

        if (op == LDR_W && pc + size < end) {
            Pc next = pc + size;
            if (!control_flow_targets[next - start]) {
                int next_op = get_opcode(vm, next);
                if (next_op == SX4) {
                    int rd_ldr = vm->text_seg[pc   + 1] & 0xFF;
                    int rd_sx4 = vm->text_seg[next + 1] & 0xFF;
                    int rs_sx4 = (vm->text_seg[next + 1] >> 8) & 0xFF;
                    if (rd_ldr == rd_sx4 && rd_sx4 == rs_sx4) {
                        emit_mov_nop(vm, next);
                        opt_count++;
                    }
                }
            }
        }
        pc += size;
    }

    if (vm->debug_vm && opt_count > 0) {
        printf("[opt] peephole: removed %d redundant instructions\n", opt_count);
    }

    free(control_flow_targets);
}

// ========== Pass 3: Dead Code Elimination ==========
//
// Remove clearly unreachable code - conservative approach.
// Only remove code that is demonstrably dead without complex analysis.
//
// Current implementation: Just count NOP sequences from previous passes.
// Actual code removal requires careful jump target tracking which is complex.
//
// Safe patterns we can detect:
// 1. Consecutive identical LI3 to same reg (second overwrites first)
// 2. Store followed immediately by another store to same address
//

static void opt_dead_code(VirtualMachine *vm, Pc fn_start, Pc fn_end) {
    if (!vm || !vm->text_seg || !vm->text_ptr) {
        return;
    }

    Pc start = fn_start;
    Pc end = fn_end;
    int dce_count = 0;

    // Count NOPs created by previous passes (informational only)
    int nop_count = 0;
    for (Pc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);

        // Check if this is a NOP
        if (op == MOV3) {
            int rd = vm->text_seg[pc + 1] & 0xFF;
            int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
            if (rd == 0 && rs == 0) nop_count++;
        } else if (op == LI3) {
            int rd = vm->text_seg[pc + 1] & 0xFF;
            if (rd == 0 && cc_read_i64_at(vm, pc + 2) == 0) nop_count++;
        }
        pc += size;
    }

    // Pattern: MOV3 rd, rs followed by another MOV3 rd, rx -> first is dead
    // (if rd is overwritten before being read)
    for (Pc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);

        if (op == MOV3 && pc + size < end) {
            int rd1 = vm->text_seg[pc + 1] & 0xFF;
            Pc next = pc + size;
            int next_op = get_opcode(vm, next);

            if (next_op == MOV3) {
                int rd2 = vm->text_seg[next + 1] & 0xFF;
                if (rd1 == rd2 && rd1 != 0) {
                    // Consecutive MOV3 to same register - first is dead
                    emit_mov_nop(vm, pc);
                    dce_count++;
                }
            }
        }
        pc += size;
    }

    if (vm->debug_vm && (dce_count > 0 || nop_count > 0)) {
        printf("[opt] dead code: %d instructions removed, %d NOPs present\n",
               dce_count, nop_count);
    }
}

// ========== Pass 4: Bytecode Compaction ==========

static void retarget_compacted_bytecode(VirtualMachine *vm, Pc *pc_map,
                                        Pc *new_to_old,
                                        Pc old_end,
                                        Pc new_end) {
    vm->text_seg[0] = remap_pc(pc_map, old_end, vm->text_seg[0]);

    for (Pc pc = 1; pc < new_end; ) {
        Pc old_pc = new_to_old[pc];
        int op = get_opcode(vm, pc);
        int size = get_compacted_instr_size_at(vm, pc, new_end);
        if (size <= 0)
            break;

        if (op == JMP || op == CALL) {
            Pc old_target = vm->text_seg[pc + 1];
            vm->text_seg[pc + 1] = remap_pc(pc_map, old_end, old_target);
        } else if (op == JZ3 || op == JNZ3) {
            Pc old_target = vm->text_seg[pc + 2];
            vm->text_seg[pc + 2] = remap_pc(pc_map, old_end, old_target);
        } else if (op == JMPT && pc + 3 < new_end && old_pc <= old_end) {
            Pc old_table = vm->text_seg[pc + 1];
            InstrWord count = vm->text_seg[pc + 2];
            Pc old_default = vm->text_seg[pc + 3];
            Pc new_table = remap_pc(pc_map, old_end, old_table);
            vm->text_seg[pc + 1] = new_table;
            vm->text_seg[pc + 3] = remap_pc(pc_map, old_end, old_default);
            if (new_table + (Pc)count <= new_end) {
                for (InstrWord i = 0; i < count; i++) {
                    Pc entry = new_table + (Pc)i;
                    vm->text_seg[entry] =
                        remap_pc(pc_map, old_end, vm->text_seg[entry]);
                }
            }
        } else if (op == LTA3) {
            remap_text_byte_offset_at(vm, pc + 2, pc_map, old_end);
        }

        pc += size;
    }

    remap_function_metadata(vm->compiler.globals, pc_map, old_end);

    if (vm->dbg.source_map) {
        for (int i = 0; i < vm->dbg.source_map_count; i++) {
            long long pc = vm->dbg.source_map[i].pc_offset;
            if (pc >= 0 && (Pc)pc <= old_end)
                vm->dbg.source_map[i].pc_offset =
                    remap_pc(pc_map, old_end, (Pc)pc);
        }
    }

    for (int i = 0; i < vm->compiler.num_data_relocs; i++) {
        if (vm->compiler.data_relocs[i].target_segment != 1)
            continue;
        Pc old_pc = cc_byte_offset_to_pc(
            vm->compiler.data_relocs[i].target_offset);
        if (old_pc == CCCC_INVALID_PC || old_pc > old_end)
            continue;
        Pc new_pc = remap_pc(pc_map, old_end, old_pc);
        long long new_offset = cc_pc_to_byte_offset(new_pc);
        vm->compiler.data_relocs[i].target_offset = new_offset;
        long long value = new_offset + vm->compiler.data_relocs[i].addend;
        *(long long *)(vm->data_seg +
                       vm->compiler.data_relocs[i].data_offset) = value;
    }
}

static void opt_compact_bytecode(VirtualMachine *vm, OptReplacement *repls) {
    if (!vm || !vm->text_seg || !vm->text_ptr)
        return;

    Pc old_end = vm->text_ptr + 1;
    Pc *pc_map = calloc((size_t)old_end + 1, sizeof(Pc));
    Pc *new_to_old = calloc((size_t)old_end + 8, sizeof(Pc));
    if (!pc_map || !new_to_old)
        error("out of memory");

    InstrWord *new_text = malloc(((size_t)old_end + 8) *
                                    sizeof(InstrWord));
    if (!new_text)
        error("out of memory");

    size_t cap = (size_t)old_end + 8;
    Pc out = 1;
    new_text[0] = vm->text_seg[0];
    new_to_old[0] = 0;

    int removed = 0;
    int expanded = 0;

    for (Pc pc = 1; pc < old_end; ) {
        int op = get_opcode(vm, pc);
        int old_size = get_instr_size_at(vm, pc, old_end);
        if (old_size <= 0)
            break;

        Pc next = pc + (Pc)old_size;
        bool remove = !repls[pc].active && is_nop_at(vm, pc);
        if (!remove && !repls[pc].active && next < old_end)
            remove = li_matches_replacement(vm, pc, &repls[next]);
        int new_size = remove ? 0 : (repls[pc].active ? repls[pc].nwords
                                                       : old_size);
        pc_map[pc] = out;
        for (int i = 1; i < old_size && pc + (Pc)i <= old_end; i++)
            pc_map[pc + (Pc)i] = out;
        if (op == JMPT && pc + 3 < old_end) {
            Pc table_pc = vm->text_seg[pc + 1];
            InstrWord count = vm->text_seg[pc + 2];
            if (table_pc == pc + 4 &&
                table_pc + (Pc)count <= old_end) {
                for (InstrWord i = 0; i < count; i++)
                    pc_map[table_pc + (Pc)i] =
                        out + 4 + (Pc)i;
            }
        }

        if (remove) {
            removed++;
            pc += old_size;
            continue;
        }

        if ((size_t)out + (size_t)new_size + 1 > cap) {
            cap = (cap * 2) + (size_t)new_size + 8;
            InstrWord *grown =
                realloc(new_text, cap * sizeof(InstrWord));
            Pc *grown_old = realloc(new_to_old, cap * sizeof(Pc));
            if (!grown || !grown_old)
                error("out of memory");
            new_text = grown;
            new_to_old = grown_old;
        }

        if (repls[pc].active) {
            memcpy(&new_text[out], repls[pc].words,
                   (size_t)new_size * sizeof(InstrWord));
            if (new_size != old_size)
                expanded++;
        } else {
            memcpy(&new_text[out], &vm->text_seg[pc],
                   (size_t)old_size * sizeof(InstrWord));
        }
        for (int i = 0; i < new_size; i++)
            new_to_old[out + (Pc)i] = pc;

        out += (Pc)new_size;
        pc += old_size;
    }
    pc_map[old_end] = out;

    if (out != old_end || removed > 0 || expanded > 0) {
        if (vm_text_ensure_count(vm, out + 1) != 0)
            error("optimizer: text segment overflow during compaction");
        memcpy(&vm->text_seg[1], &new_text[1],
               ((size_t)out - 1) * sizeof(InstrWord));
        vm->text_ptr = out - 1;
        retarget_compacted_bytecode(vm, pc_map, new_to_old, old_end, out);
        if (vm->debug_vm) {
            printf("[opt] compaction: removed %d NOPs, expanded %d folds, "
                   "text words %u -> %u\n",
                   removed, expanded, old_end, out);
        }
    }

    free(new_text);
    free(new_to_old);
    free(pc_map);
}

// ========== Pass 4: Copy Propagation ==========
//
// Eliminates register-to-register copy chains by substituting uses of a
// copied register with the ultimate source register.  After substitution,
// MOV3/FMOV3 instructions whose destination is no longer used are converted
// to NOP for the subsequent compaction pass.
//
// Conservative at control-flow boundaries and call sites: all copy facts are
// cleared at branch targets and after CALL-family instructions.
//
// Two sub-passes on the same [fn_start, fn_end) range:
//   A: Forward — record copy facts, chain-collapse MOV3 chains, substitute
//      source operands (rs1/rs2 — bytes 1-2 of the operand word) in all
//      non-CF instructions.
//   B: Use-count + NOP — count register appearances in source positions;
//      NOP any MOV3/FMOV3 whose destination is never read.

// Returns true when both source operands of op come from the float register
// file (fregs[]).  Mixed ops (I2F3, FLDR, FSTR, …) return false so their
// sources are substituted from the integer copy map, which is correct for
// their integer address/index operands.
static bool op_is_float_src(int op) {
    switch (op) {
    case FMOV3:
    case FADD3: case FSUB3: case FMUL3: case FDIV3: case FNEG3:
    case FADD3_F32: case FSUB3_F32: case FMUL3_F32: case FDIV3_F32:
    case FNEG3_F32: case FROUND_F32:
    case FEQ3: case FNE3: case FLT3: case FLE3: case FGT3: case FGE3:
    case FEQ3_F32: case FNE3_F32: case FLT3_F32: case FLE3_F32:
    case FGT3_F32: case FGE3_F32:
    case F2I3: case F2I3_F32: case FR2R: case FR2R_F32:
        return true;
    default:
        return false;
    }
}

// Returns true for opcodes whose byte 0 of the operand word is an INTEGER
// SOURCE register (not a destination).  Used to prevent KILL_INT_DEF from
// NOP-ing the MOV3 that produced the value read by these instructions.
static bool op_byte0_is_int_src(int op) {
    switch (op) {
    // Stores: byte 0 is the value register being written to memory.
    case STR_B: case STR_H: case STR_W: case STR_D:
    case STR_INDEX_B: case STR_INDEX_H: case STR_INDEX_W: case STR_INDEX_D:
    case STR_LOCAL_B: case STR_LOCAL_H: case STR_LOCAL_W: case STR_LOCAL_D:
    // Atomic store: byte 0 is the value register; byte 1 is the pointer.
    case ASTR:
    // Conditional branches: byte 0 is the condition register.
    case JZ3: case JNZ3:
    // Indirect control-flow: byte 0 is the jump/call-target source register.
    case JMPI:
    case CALLN: case CALLI:
    // Stack push: byte 0 is the register whose value is pushed.
    case PSH3:
    // Pointer and type safety checks: byte 0 is the pointer source register.
    case CHKP3: case CHKA3: case CHKT3: case CHKPA:
    // Dangling-pointer tracker: byte 0 is the base-pointer source register.
    case MARKA:
        return true;
    default:
        return false;
    }
}

// Returns true for opcodes whose byte 0 of the operand word is a FLOAT
// register (either float destination or float source value for stores).
// Used to avoid confusing float and integer register tracking.
static bool op_byte0_is_float(int op) {
    switch (op) {
    case FMOV3:
    case FADD3: case FSUB3: case FMUL3: case FDIV3: case FNEG3:
    case FADD3_F32: case FSUB3_F32: case FMUL3_F32: case FDIV3_F32:
    case FNEG3_F32: case FROUND_F32:
    case FLDR: case FLDR_F32:
    case FLDR_INDEX: case FLDR_INDEX_F32:
    case FLDR_LOCAL: case FLDR_LOCAL_F32:
    case FSTR: case FSTR_F32:
    case FSTR_INDEX: case FSTR_INDEX_F32:
    case FSTR_LOCAL: case FSTR_LOCAL_F32:
        return true;
    default:
        return false;
    }
}

// Returns true for opcodes that READ a float register from byte 0 (float stores).
// These are sources, not destinations — KILL_FLOAT_DEF must not fire for them.
static bool op_byte0_is_float_src(int op) {
    switch (op) {
    case FSTR: case FSTR_F32:
    case FSTR_INDEX: case FSTR_INDEX_F32:
    case FSTR_LOCAL: case FSTR_LOCAL_F32:
        return true;
    default:
        return false;
    }
}

// Kept for sub-pass B use-count on stores (byte 0 is any kind of source).
static bool op_byte0_is_src(int op) {
    return op_byte0_is_int_src(op) || op_byte0_is_float(op);
}

static void opt_copy_prop(VirtualMachine *vm, Pc fn_start, Pc fn_end) {
    if (!vm || !vm->text_seg || !vm->text_ptr)
        return;

    Pc start = fn_start;
    Pc end   = fn_end;

    bool *cf_targets = build_control_flow_targets(vm, start, end);

    // copy_of[r]  = s  —  integer register r is a copy of integer register s
    // fcopy_of[r] = s  —  float register r is a copy of float register s
    // -1 = no active copy fact for r
    int copy_of[NUM_REGS];
    int fcopy_of[NUM_REGS];
    for (int i = 0; i < NUM_REGS; i++)
        copy_of[i] = fcopy_of[i] = -1;

    int prop_count = 0;
    int nop_count  = 0;

    // ---- Sub-pass A: Forward copy propagation ----
    for (Pc pc = start; pc < end; ) {
        int op   = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);
        if (size <= 0)
            break;

        // Clear all copy facts at control-flow join points.
        if (pc != start && cf_targets[pc - start])
            for (int i = 0; i < NUM_REGS; i++)
                copy_of[i] = fcopy_of[i] = -1;

        if (op == MOV3) {
            int rd = (int)(vm->text_seg[pc + 1] & 0xFF);
            int rs = (int)((vm->text_seg[pc + 1] >> 8) & 0xFF);

            if (rd > REG_ZERO && rd != rs) {
                // Chain-resolve: follow rs back to the ultimate source.
                int root = (rs < NUM_REGS && copy_of[rs] >= 0) ? copy_of[rs] : rs;
                copy_of[rd] = root;
                // Rewrite this MOV3 to point at the root (collapses chains).
                if (root != rs) {
                    vm->text_seg[pc + 1] = ENCODE_RR(rd, root);
                    prop_count++;
                }
                // Kill stale copy facts that pointed at rd.
                for (int i = 1; i < NUM_REGS; i++)
                    if (copy_of[i] == rd) copy_of[i] = -1;
            } else if (rd > REG_ZERO) {
                copy_of[rd] = -1;
                for (int i = 1; i < NUM_REGS; i++)
                    if (copy_of[i] == rd) copy_of[i] = -1;
            }

        } else if (op == FMOV3) {
            int rd = (int)(vm->text_seg[pc + 1] & 0xFF);
            int rs = (int)((vm->text_seg[pc + 1] >> 8) & 0xFF);

            if (rd > REG_ZERO && rd != rs) {
                int root = (rs < NUM_REGS && fcopy_of[rs] >= 0) ? fcopy_of[rs] : rs;
                fcopy_of[rd] = root;
                if (root != rs) {
                    vm->text_seg[pc + 1] = ENCODE_RR(rd, root);
                    prop_count++;
                }
                for (int i = 1; i < NUM_REGS; i++)
                    if (fcopy_of[i] == rd) fcopy_of[i] = -1;
            } else if (rd > REG_ZERO) {
                fcopy_of[rd] = -1;
                for (int i = 1; i < NUM_REGS; i++)
                    if (fcopy_of[i] == rd) fcopy_of[i] = -1;
            }

        } else {
            switch (op) {
            // Conditional branches: fall-through retains copy facts.
            // Substitute the condition register (byte 0) if a fact exists.
            // The taken target is already a CF target and will be cleared there.
            case JZ3:
            case JNZ3:
                if (size >= 2) {
                    InstrWord w = vm->text_seg[pc + 1];
                    int rs = (int)(w & 0xFF);
                    if (rs > REG_ZERO && rs < NUM_REGS && copy_of[rs] >= 0) {
                        vm->text_seg[pc + 1] = (w & ~(InstrWord)0xFFu)
                                             | (InstrWord)copy_of[rs];
                        prop_count++;
                    }
                }
                break;

            // Unconditional control-flow: clear all copy facts.
            case JMP:
            case JMPT:
            case JMPI:
            case CALL:
            case CALLT:
            case CALLI:
            case CALLN:
            case CALLF:
            case ENT3:
            case LEV3:
            // Zero-operand instructions that clobber A-registers implicitly:
            // their implicit writes are invisible to the size>=2 scan in the
            // default case, so stale copy facts would survive and cause wrong
            // substitutions downstream.  Clear conservatively (mirrors sub-pass B).
            case LONGJMP:
            case DLOPEN: case DLSYM: case DLCLOSE: case DLERROR:
            case MALC: case CALC: case REALC:
            case MFRE:
            case RETBUF:
            case SETJMP:
            case MCPY:
            case WIDE_ADD: case WIDE_SUB: case WIDE_MUL: case WIDE_DIV:
            case WIDE_MOD: case WIDE_SHL: case WIDE_SHR: case WIDE_USHR:
            case VSIGNAL:
            case BTRAP:
                for (int i = 0; i < NUM_REGS; i++)
                    copy_of[i] = fcopy_of[i] = -1;
                break;

            default:
                // Substitute rs1 (byte 1) and rs2 (byte 2) of the operand word
                // using the appropriate copy map, then kill the destination
                // register (byte 0).  Applies to all sizes — byte 3 (scale /
                // bitwidth) is left untouched.
                if (size >= 2) {
                    InstrWord w = vm->text_seg[pc + 1];
                    int rd  = (int)(w & 0xFF);
                    int rs1 = (int)((w >> 8) & 0xFF);
                    int rs2 = (int)((w >> 16) & 0xFF);

                    int *cop = op_is_float_src(op) ? fcopy_of : copy_of;

                    bool changed = false;
                    if (rs1 > REG_ZERO && rs1 < NUM_REGS && cop[rs1] >= 0) {
                        rs1 = cop[rs1]; changed = true;
                    }
                    if (rs2 > REG_ZERO && rs2 < NUM_REGS && cop[rs2] >= 0) {
                        rs2 = cop[rs2]; changed = true;
                    }
                    if (changed) {
                        // Update bytes 1-2; preserve bytes 0 (rd) and 3 (scale).
                        vm->text_seg[pc + 1] = (w & ~(InstrWord)0x00FFFF00u)
                                             | ((InstrWord)rs1 << 8)
                                             | ((InstrWord)rs2 << 16);
                        prop_count++;
                    }

                    // Kill copy facts for rd (it is (re)defined by this instruction).
                    if (rd > REG_ZERO && rd < NUM_REGS) {
                        copy_of[rd]  = -1;
                        fcopy_of[rd] = -1;
                        for (int i = 1; i < NUM_REGS; i++) {
                            if (copy_of[i]  == rd) copy_of[i]  = -1;
                            if (fcopy_of[i] == rd) fcopy_of[i] = -1;
                        }
                    }
                }
                break;
            }
        }

        pc += size;
    }

    // ---- Sub-pass B: Forward dead-MOV3 elimination ----
    //
    // Tracks the most recent MOV3 that defined each integer register.
    // When a register is re-defined (by any instruction) before its value has
    // been read, the earlier MOV3 is dead and is NOP'd.
    //
    // Tracking resets conservatively at:
    //   - CF join targets (loop headers, branch destinations)
    //   - Conditional branches (JZ3/JNZ3): the taken path is unknown, so we
    //     abandon tracking rather than risk an incorrect NOP.
    //   - Unconditional CF instructions (JMP, CALL, etc.)
    //
    // Integer MOV3 and float FMOV3 dead copies are eliminated here.
    // For integers (sub-pass B): MOV3 is dead if its destination is re-defined
    // before being read (write-after-write within the same basic block).
    // For floats (sub-pass B + C): FMOV3 write-after-write is caught here;
    // FMOV3 instructions whose destination has zero global uses after sub-pass
    // A propagation are caught by the subsequent sub-pass C use-count scan.

    Pc  last_mov_pc[NUM_REGS];
    bool mov_r_live[NUM_REGS];
    Pc  last_fmov_pc[NUM_REGS];
    bool fmov_r_live[NUM_REGS];
    for (int i = 0; i < NUM_REGS; i++) {
        last_mov_pc[i]  = (Pc)-1;
        mov_r_live[i]   = false;
        last_fmov_pc[i] = (Pc)-1;
        fmov_r_live[i]  = false;
    }

#define RESET_MOV_TRACKING() do { \
    for (int _i = 0; _i < NUM_REGS; _i++) { \
        last_mov_pc[_i]  = (Pc)-1; \
        mov_r_live[_i]   = false;  \
        last_fmov_pc[_i] = (Pc)-1; \
        fmov_r_live[_i]  = false;  \
    } \
} while (0)

#define MARK_INT_USE(r) do { \
    int _r = (r); \
    if (_r > REG_ZERO && _r < NUM_REGS && last_mov_pc[_r] != (Pc)-1) \
        mov_r_live[_r] = true; \
} while (0)

#define KILL_INT_DEF(r) do { \
    int _r = (r); \
    if (_r > REG_ZERO && _r < NUM_REGS) { \
        if (last_mov_pc[_r] != (Pc)-1 && !mov_r_live[_r]) { \
            emit_mov_nop(vm, last_mov_pc[_r]); \
            nop_count++; \
        } \
        last_mov_pc[_r] = (Pc)-1; \
        mov_r_live[_r]  = false; \
    } \
} while (0)

#define MARK_FLOAT_USE(r) do { \
    int _r = (r); \
    if (_r > REG_ZERO && _r < NUM_REGS && last_fmov_pc[_r] != (Pc)-1) \
        fmov_r_live[_r] = true; \
} while (0)

#define KILL_FLOAT_DEF(r) do { \
    int _r = (r); \
    if (_r > REG_ZERO && _r < NUM_REGS) { \
        if (last_fmov_pc[_r] != (Pc)-1 && !fmov_r_live[_r]) { \
            emit_mov_nop(vm, last_fmov_pc[_r]); \
            nop_count++; \
        } \
        last_fmov_pc[_r] = (Pc)-1; \
        fmov_r_live[_r]  = false; \
    } \
} while (0)

    for (Pc pc = start; pc < end; ) {
        if (pc != start && cf_targets[pc - start])
            RESET_MOV_TRACKING();

        int op   = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);
        if (size <= 0) break;

        if (op == JZ3 || op == JNZ3) {
            // Conditional branch: mark condition register (byte 0) as used,
            // then conservatively reset — the taken path is unknown.
            if (size >= 2) {
                int rs = (int)(vm->text_seg[pc + 1] & 0xFF);
                MARK_INT_USE(rs);
            }
            RESET_MOV_TRACKING();

        } else if (op == MOV3) {
            if (size >= 2) {
                int rd = (int)(vm->text_seg[pc + 1] & 0xFF);
                int rs = (int)((vm->text_seg[pc + 1] >> 8) & 0xFF);
                if (rd > REG_ZERO && rd < NUM_REGS) {
                    // If previous MOV3 to rd was never used, it is dead.
                    if (last_mov_pc[rd] != (Pc)-1 && !mov_r_live[rd]) {
                        emit_mov_nop(vm, last_mov_pc[rd]);
                        nop_count++;
                    }
                    last_mov_pc[rd] = pc;
                    mov_r_live[rd]  = false;
                }
                MARK_INT_USE(rs);
            }

        } else if (op == FMOV3) {
            if (size >= 2) {
                int rd = (int)(vm->text_seg[pc + 1] & 0xFF);
                int rs = (int)((vm->text_seg[pc + 1] >> 8) & 0xFF);
                if (rd > REG_ZERO && rd < NUM_REGS) {
                    // If previous FMOV3 to rd was never used, it is dead.
                    if (last_fmov_pc[rd] != (Pc)-1 && !fmov_r_live[rd]) {
                        emit_mov_nop(vm, last_fmov_pc[rd]);
                        nop_count++;
                    }
                    last_fmov_pc[rd] = pc;
                    fmov_r_live[rd]  = false;
                }
                MARK_FLOAT_USE(rs);
            }

        } else if (op == AXCHG || op == ACAS) {
            // AXCHG/ACAS carry a width_enc i64 immediate in their operand words
            // (layout: [opcode][width_enc_lo32][width_enc_hi32]), NOT a register
            // encoding.  The generic size>=2 decode below must be skipped for
            // these opcodes — it would misread the low word of width_enc as a
            // register encoding and fire KILL_INT_DEF on its low byte, silently
            // NOPing a live MOV3 if that byte coincidentally matches a pending
            // destination register (e.g. r8/r9 for a 4-byte atomic).
            //
            // Precise implicit register model (verified from ops.c / codegen.c):
            //   AXCHG: reads A0 (addr), A1 (new val); writes A0 (old val).
            //   ACAS:  reads A0 (obj ptr), A1 (exp ptr), A2 (desired);
            //          writes A0 (bool result).  Failure update of *A1 is a
            //          memory write through the pointer, not a register write.
            //
            // Mark uses before killing the A0 def so a pending MOV3 into A0
            // is preserved if it is still live (matches the SETJMP pattern).
            MARK_INT_USE(REG_A0);
            MARK_INT_USE(REG_A1);
            if (op == ACAS)
                MARK_INT_USE(REG_A2);
            KILL_INT_DEF(REG_A0);

        } else {
            if (size >= 2) {
                InstrWord w = vm->text_seg[pc + 1];
                int rd  = (int)(w & 0xFF);
                int rs1 = (int)((w >> 8) & 0xFF);
                int rs2 = (int)((w >> 16) & 0xFF);

                // Mark integer register uses.
                if (op_byte0_is_int_src(op))
                    MARK_INT_USE(rd);
                if (!op_is_float_src(op)) {
                    MARK_INT_USE(rs1);
                    MARK_INT_USE(rs2);
                }

                // Mark float register uses for instructions whose rs1/rs2 are floats.
                if (op_is_float_src(op)) {
                    MARK_FLOAT_USE(rs1);
                    MARK_FLOAT_USE(rs2);
                }
                // All float stores (FSTR/FSTR_F32/FSTR_INDEX/FSTR_INDEX_F32/
                // FSTR_LOCAL/FSTR_LOCAL_F32): byte 0 is the float value being stored.
                if (op_byte0_is_float_src(op))
                    MARK_FLOAT_USE(rd);

                // Kill integer register definition at byte 0 if this instruction
                // writes an integer result there (not a float def, not a store).
                if (!op_byte0_is_src(op) && !op_byte0_is_float(op))
                    KILL_INT_DEF(rd);

                // Kill float register definition at byte 0 if this instruction
                // writes a float result there (not a float store).
                if (op_byte0_is_float(op) && !op_byte0_is_float_src(op))
                    KILL_FLOAT_DEF(rd);
            }

            // Unconditional control-flow and zero-operand register-clobbering
            // instructions: reset or conservatively mark A-register uses.
            // Zero-operand instructions have no operand words so their implicit
            // register reads/writes are invisible to the size>=2 scan above.
            switch (op) {
            case JMP: case JMPT: case JMPI:
            case CALL: case CALLT: case CALLI: case CALLN: case CALLF:
            case ENT3: case LEV3:
                RESET_MOV_TRACKING();
                break;

            // MCPY(dest=A0, src=A1, count=A2): reads A0, A1, A2.
            case MCPY:
                MARK_INT_USE(REG_A0);
                MARK_INT_USE(REG_A1);
                MARK_INT_USE(REG_A2);
                break;

            // MALC/CALC(size=A0): reads A0, writes A0.
            case MALC: case CALC:
                MARK_INT_USE(REG_A0);
                KILL_INT_DEF(REG_A0);
                break;

            // MFRE(ptr=A0): reads A0.
            case MFRE:
                MARK_INT_USE(REG_A0);
                break;

            // REALC(ptr=A0, size=A1): reads A0, A1, writes A0.
            case REALC:
                MARK_INT_USE(REG_A0);
                MARK_INT_USE(REG_A1);
                KILL_INT_DEF(REG_A0);
                break;

            // RETBUF: writes A0 (return buffer address from pool).
            case RETBUF:
                KILL_INT_DEF(REG_A0);
                break;

            // SETJMP(jmp_buf=A0): reads A0, writes A0.
            case SETJMP:
                MARK_INT_USE(REG_A0);
                KILL_INT_DEF(REG_A0);
                break;

            // All other zero-operand instructions (LONGJMP, DLOPEN, WIDE_* etc.):
            // reset conservatively — their A-register usage is too varied.
            case LONGJMP:
            case DLOPEN: case DLSYM: case DLCLOSE: case DLERROR:
            case WIDE_ADD: case WIDE_SUB: case WIDE_MUL: case WIDE_DIV:
            case WIDE_MOD: case WIDE_SHL: case WIDE_SHR: case WIDE_USHR:
            case VSIGNAL:
            case BTRAP:
                RESET_MOV_TRACKING();
                break;

            default:
                break;
            }
        }

        pc += size;
    }

#undef RESET_MOV_TRACKING
#undef MARK_INT_USE
#undef KILL_INT_DEF
#undef MARK_FLOAT_USE
#undef KILL_FLOAT_DEF

    // ---- Sub-pass C: Global zero-use FMOV3 elimination ----
    //
    // After sub-pass A propagates copy facts and substitutes sources, a FMOV3
    // whose destination register had ALL its uses rewritten (e.g. by the float
    // local promotion read pattern) will have ZERO remaining reads in the
    // entire function.  Sub-pass B's basic-block write-after-write tracking
    // cannot catch this case, so we do a full-function use-count scan here.
    //
    // Approach:
    //   1. Count every float register read across the entire [start, end) range.
    //   2. NOP any FMOV3 whose destination (rd) has use_count == 0.
    //
    // This is safe: if use_count[rd] == 0, no instruction in the function
    // reads rd — the FMOV3 has no live consumers and its result is garbage-
    // collected by the next compaction pass.
    {
        int use_count[NUM_REGS];
        for (int i = 0; i < NUM_REGS; i++)
            use_count[i] = 0;

        for (Pc pc2 = start; pc2 < end; ) {
            int op2   = get_opcode(vm, pc2);
            int size2 = get_instr_size_at(vm, pc2, end);
            if (size2 <= 0) break;

            if (size2 >= 2) {
                InstrWord w2 = vm->text_seg[pc2 + 1];
                int rs1_2 = (int)((w2 >> 8) & 0xFF);
                int rs2_2 = (int)((w2 >> 16) & 0xFF);

                if (op2 == FMOV3) {
                    // rs (byte 1) is the float source.
                    if (rs1_2 > REG_ZERO && rs1_2 < NUM_REGS)
                        use_count[rs1_2]++;
                } else if (op_is_float_src(op2)) {
                    if (rs1_2 > REG_ZERO && rs1_2 < NUM_REGS)
                        use_count[rs1_2]++;
                    if (rs2_2 > REG_ZERO && rs2_2 < NUM_REGS)
                        use_count[rs2_2]++;
                }
                // All float stores: byte 0 is the float value being stored.
                if (op_byte0_is_float_src(op2)) {
                    int rd2 = (int)(w2 & 0xFF);
                    if (rd2 > REG_ZERO && rd2 < NUM_REGS)
                        use_count[rd2]++;
                }
            }

            // CALL-family implicitly reads float argument registers FREG_A0–A7
            // (indices 10–17).  Count them as uses so that FMOV3 instructions
            // that set up float call arguments are never eliminated here.
            switch (op2) {
            case CALL: case CALLT: case CALLI: case CALLN: case CALLF:
                for (int fa = FREG_A0; fa <= FREG_A7; fa++)
                    use_count[fa]++;
                break;
            default:
                break;
            }

            pc2 += size2;
        }

        for (Pc pc2 = start; pc2 < end; ) {
            int op2   = get_opcode(vm, pc2);
            int size2 = get_instr_size_at(vm, pc2, end);
            if (size2 <= 0) break;

            if (op2 == FMOV3 && size2 >= 2) {
                int rd2 = (int)(vm->text_seg[pc2 + 1] & 0xFF);
                if (rd2 > REG_ZERO && rd2 < NUM_REGS && use_count[rd2] == 0) {
                    emit_mov_nop(vm, pc2);
                    nop_count++;
                }
            }
            pc2 += size2;
        }
    }

    free(cf_targets);

    if (vm->debug_vm && (prop_count > 0 || nop_count > 0))
        printf("[opt] copy-prop: rewrote %d uses, eliminated %d dead copies\n",
               prop_count, nop_count);
}

// ========== Pass 5: CSE for [[gnu::const]] Functions ==========
//
// Common-subexpression elimination for const functions.
// If f(x) is called twice with the same argument value numbers and f is
// marked [[gnu::const]], the second call is replaced with a MOV3 from the
// register that holds the first result.
//
// Runs after compaction on the final bytecode.  CALL (2 words) and MOV3
// (2 words) are the same size, so replacement is in-place — no second
// compaction pass is needed.
//
// Value numbering tracks:
//   VN_CONST      — register holds a known compile-time constant
//   VN_LOCAL_SLOT — register was loaded from a specific bp-relative slot
//
// CSE fires when all args of a const function have the same VNumbers across
// two call sites within the same basic block.  It does NOT fire for float/
// double arguments (which use FREG_A* instead of REG_A*), or after any
// intervening control-flow boundary or CALL (conservative).

#define MAX_CSE_ENTRIES 32

typedef enum { VN_UNKNOWN = 0, VN_CONST, VN_LOCAL_SLOT } VNKind;

typedef struct {
    VNKind kind;
    long long const_val;    // VN_CONST: the constant value
    long long local_offset; // VN_LOCAL_SLOT: bp-relative byte offset
} VNumber;

typedef struct {
    bool      active;
    bool      valid;        // false if saved_reg was clobbered after the call
    Pc    target_addr;
    int       nargs;
    VNumber   arg_vns[8];
    int       saved_reg;    // register that caches the first result (-1 = not yet found)
} CseEntry;

static bool vn_equal(const VNumber *a, const VNumber *b) {
    if (a->kind != b->kind || a->kind == VN_UNKNOWN)
        return false;
    if (a->kind == VN_CONST)
        return a->const_val == b->const_val;
    return a->local_offset == b->local_offset;
}

static Obj *cse_lookup_const_fn(VirtualMachine *vm, Pc addr) {
    for (Obj *fn = vm->compiler.globals; fn; fn = fn->next)
        if (fn->is_function && fn->is_func_const && (Pc)fn->code_addr == addr)
            return fn;
    return NULL;
}

static int cse_count_params(Obj *fn) {
    int n = 0;
    for (Obj *p = fn->params; p; p = p->next)
        n++;
    return n;
}

static bool cse_has_float_params(Obj *fn) {
    for (Obj *p = fn->params; p; p = p->next)
        if (p->ty && is_flonum(p->ty))
            return true;
    return false;
}

static CseEntry *cse_find(CseEntry *cache, int ncache,
                          Pc addr, int nargs, VNumber *arg_vns) {
    for (int i = 0; i < ncache; i++) {
        CseEntry *e = &cache[i];
        if (!e->active || e->target_addr != addr || e->nargs != nargs)
            continue;
        bool match = true;
        for (int j = 0; j < nargs; j++) {
            if (!vn_equal(&e->arg_vns[j], &arg_vns[j])) {
                match = false;
                break;
            }
        }
        if (match)
            return e;
    }
    return NULL;
}

static void cse_reset_vn(VNumber *vn) {
    for (int i = 0; i < MAX_TRACKED_REGS; i++)
        vn[i].kind = VN_UNKNOWN;
    vn[REG_ZERO].kind = VN_CONST;
    vn[REG_ZERO].const_val = 0;
}

static void cse_invalidate_slot(VNumber *vn, long long offset) {
    for (int i = 1; i < MAX_TRACKED_REGS; i++)
        if (vn[i].kind == VN_LOCAL_SLOT && vn[i].local_offset == offset)
            vn[i].kind = VN_UNKNOWN;
}

static void cse_invalidate_reg(CseEntry *cache, int ncache, int rd) {
    for (int i = 0; i < ncache; i++)
        if (cache[i].active && cache[i].saved_reg == rd)
            cache[i].valid = false;
}

static void opt_cse_const_calls(VirtualMachine *vm, Pc fn_start, Pc fn_end) {
    if (!vm || !vm->text_seg || !vm->text_ptr)
        return;
    if (!vm->compiler.globals)
        return;

    Pc start = fn_start;
    Pc end = fn_end;

    bool *cf_targets = build_control_flow_targets(vm, start, end);

    VNumber vn[MAX_TRACKED_REGS];
    CseEntry cache[MAX_CSE_ENTRIES];
    int ncache = 0;
    int pending = -1;
    int cse_count = 0;
    // After CSE replaces a CALL with MOV3 REG_A0, saved_reg, the very next
    // MOV3 that writes saved_reg back from REG_A0 is an idempotent re-save
    // (same value returned to the same register).  Track it here so the
    // MOV3 case can skip invalidating the cache entry for saved_reg.
    int cse_re_save_reg = -1;

    cse_reset_vn(vn);
    memset(cache, 0, sizeof(cache));

    for (Pc pc = start; pc < end; ) {
        int op = get_opcode(vm, pc);
        int size = get_instr_size_at(vm, pc, end);
        if (size <= 0)
            break;

        // At control-flow targets reset all tracking (conservative).
        if (pc != start && cf_targets[pc - start]) {
            cse_reset_vn(vn);
            for (int i = 0; i < ncache; i++)
                cache[i].valid = false;
            pending = -1;
            cse_re_save_reg = -1;
        }

        switch (op) {

        // ---- Value number tracking ----
        case LI3: {
            int rd = vm->text_seg[pc + 1] & 0xFF;
            if (rd > REG_ZERO && rd < MAX_TRACKED_REGS) {
                vn[rd].kind      = VN_CONST;
                vn[rd].const_val = cc_read_i64_at(vm, pc + 2);
                cse_invalidate_reg(cache, ncache, rd);
            }
            break;
        }
        case MOV3: {
            int rd = vm->text_seg[pc + 1] & 0xFF;
            int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
            if (rd > REG_ZERO && rd < MAX_TRACKED_REGS) {
                // Check for the idempotent re-save that codegen emits right
                // after a call: MOV3 saved_reg, REG_A0.  When this follows a
                // CSE'd CALL (replaced with MOV3 REG_A0, saved_reg), REG_A0
                // already holds saved_reg's value, so the write is a no-op
                // and the cache entry for saved_reg must NOT be invalidated.
                bool is_cse_re_save = (rs == REG_A0 &&
                                       rd == cse_re_save_reg &&
                                       cse_re_save_reg >= 0);
                cse_re_save_reg = -1; // consume the flag

                if (!is_cse_re_save)
                    cse_invalidate_reg(cache, ncache, rd);

                // Capture result of a pending const call: the very first
                // MOV3 that copies REG_A0 into another register after a
                // const CALL is the canonical result-save.
                if (pending >= 0 && rs == REG_A0 && rd != REG_A0) {
                    if (cache[pending].saved_reg < 0)
                        cache[pending].saved_reg = rd;
                    pending = -1;
                }
                // Propagate value number
                if (rs < MAX_TRACKED_REGS)
                    vn[rd] = vn[rs];
                else
                    vn[rd].kind = VN_UNKNOWN;
            }
            break;
        }
        case LDR_LOCAL_B:
        case LDR_LOCAL_H:
        case LDR_LOCAL_W:
        case LDR_LOCAL_D: {
            int rd = vm->text_seg[pc + 1] & 0xFF;
            if (rd > REG_ZERO && rd < MAX_TRACKED_REGS) {
                vn[rd].kind         = VN_LOCAL_SLOT;
                vn[rd].local_offset = cc_read_i64_at(vm, pc + 2);
                cse_invalidate_reg(cache, ncache, rd);
            }
            break;
        }
        case STR_LOCAL_B:
        case STR_LOCAL_H:
        case STR_LOCAL_W:
        case STR_LOCAL_D: {
            long long off = cc_read_i64_at(vm, pc + 2);
            cse_invalidate_slot(vn, off);
            // A store to a local slot doesn't modify the register file,
            // so saved_reg cache entries remain valid.
            break;
        }

        // ---- CSE: direct call to const function ----
        case CALL: {
            Pc target = vm->text_seg[pc + 1];
            Obj *fn = cse_lookup_const_fn(vm, target);
            if (fn && !cse_has_float_params(fn)) {
                int nargs = cse_count_params(fn);
                if (nargs <= 8) {
                    VNumber arg_vns[8] = {{0}};
                    bool all_known = true;
                    for (int i = 0; i < nargs; i++) {
                        int ar = REG_A0 + i;
                        if (ar < MAX_TRACKED_REGS &&
                            vn[ar].kind != VN_UNKNOWN) {
                            arg_vns[i] = vn[ar];
                        } else {
                            all_known = false;
                            break;
                        }
                    }
                    if (all_known) {
                        CseEntry *e = cse_find(cache, ncache,
                                               target, nargs, arg_vns);
                        if (e && e->valid && e->saved_reg >= 0) {
                            // Replace CALL with MOV3 REG_A0, saved_reg.
                            // Both are 2 words — safe in-place replacement.
                            vm->text_seg[pc]     = MOV3;
                            vm->text_seg[pc + 1] = (InstrWord)REG_A0 |
                                ((InstrWord)e->saved_reg << 8);
                            cse_count++;
                            // The codegen always emits a MOV3 dest, REG_A0
                            // right after the CALL to save the result.  After
                            // CSE, REG_A0 already holds saved_reg's value, so
                            // the next MOV3 saved_reg, REG_A0 is idempotent —
                            // don't invalidate the cache entry for saved_reg.
                            cse_re_save_reg = e->saved_reg;
                        } else if (!e && ncache < MAX_CSE_ENTRIES) {
                            CseEntry *ne = &cache[ncache++];
                            ne->active     = true;
                            ne->valid      = true;
                            ne->target_addr = target;
                            ne->nargs      = nargs;
                            ne->saved_reg  = -1;
                            memcpy(ne->arg_vns, arg_vns,
                                   (size_t)nargs * sizeof(VNumber));
                            pending = ncache - 1;
                        }
                    }
                }
            }
            // CALL clobbers all tracked VN state.
            cse_reset_vn(vn);
            // pending is either already set (first call) or has just been cleared
            // by the CSE replacement above.  Reset it if we didn't just set it.
            if (pending >= 0 && cache[pending].saved_reg >= 0)
                pending = -1; // already resolved from a previous iteration
            break;
        }

        // Any other CALL-like opcode — reset VN and pending.
        case CALLT:
        case CALLI:
        case CALLN:
        case CALLF:
        case ENT3:
        case LEV3: {
            cse_reset_vn(vn);
            pending = -1;
            cse_re_save_reg = -1;
            break;
        }

        default: {
            // For any instruction that writes a destination register,
            // update VN and invalidate matching cache entries.
            if (size >= 2) {
                int rd = vm->text_seg[pc + 1] & 0xFF;
                if (rd > REG_ZERO && rd < MAX_TRACKED_REGS) {
                    // If this is a non-MOV3 instruction and pending is set,
                    // give up tracking the save register (something unusual
                    // intervened between the CALL and the expected MOV3).
                    if (pending >= 0)
                        pending = -1;
                    vn[rd].kind = VN_UNKNOWN;
                    // In-place sign/zero extension (rd == rs) upgrades the
                    // value already in rd but does not replace it with an
                    // unrelated value.  Cache entries keyed on rd remain
                    // valid — the extended result is still the const call's
                    // output.
                    bool is_inplace_extend = false;
                    if (op == SX1 || op == SX2 || op == SX4 ||
                        op == ZX1 || op == ZX2 || op == ZX4) {
                        int rs = (vm->text_seg[pc + 1] >> 8) & 0xFF;
                        is_inplace_extend = (rs == rd);
                    }
                    if (!is_inplace_extend)
                        cse_invalidate_reg(cache, ncache, rd);
                }
            }
            break;
        }
        } // end switch

        pc += size;
    }

    free(cf_targets);

    if (vm->debug_vm && cse_count > 0)
        printf("[opt] CSE const-calls: eliminated %d call%s\n",
               cse_count, cse_count == 1 ? "" : "s");
}

// ========== Pass 6: Automatic opcode fusion ==========

static bool opt_pc_is_target(const bool *targets, Pc start, Pc end, Pc pc) {
    return pc >= start && pc < end && targets[pc - start];
}

static bool opt_fuse_li3_arith(VirtualMachine *vm, const CcFusionCandidate *c,
                               OptReplacement *repls, bool *consumed,
                               Pc start, Pc end, const bool *targets) {
    (void)start;
    if (c->def_op != LI3 || (c->use_op != ADD3 && c->use_op != MUL3))
        return false;
    Pc def_pc = (Pc)c->def_pc;
    Pc use_pc = (Pc)c->use_pc;
    if (def_pc >= end || use_pc >= end || consumed[def_pc] || consumed[use_pc])
        return false;
    if (opt_pc_is_target(targets, 1, end, def_pc) ||
        opt_pc_is_target(targets, 1, end, use_pc))
        return false;

    int imm_reg = vm->text_seg[def_pc + 1] & 0xFF;
    if (imm_reg != c->reg || imm_reg == REG_ZERO)
        return false;
    long long imm = cc_read_i64_at(vm, def_pc + 2);

    int rd, rs1, rs2;
    DECODE_RRR(vm->text_seg[use_pc + 1], rd, rs1, rs2);
    if (c->use_byte != OPT_P_RS1 && c->use_byte != OPT_P_RS2)
        return false;
    int other = (c->use_byte == OPT_P_RS1) ? rs2 : rs1;
    if (other == imm_reg)
        return false;

    set_rri_replacement(repls, def_pc, c->use_op == ADD3 ? ADDI3 : MULI3,
                        rd, other, imm);
    emit_mov_nop(vm, use_pc);
    consumed[def_pc] = true;
    consumed[use_pc] = true;
    return true;
}

static bool opt_fuse_mul3_add3(VirtualMachine *vm, const CcFusionCandidate *c,
                               OptReplacement *repls, bool *consumed,
                               Pc end, const bool *targets) {
    if (c->def_op != MUL3 || c->use_op != ADD3)
        return false;
    Pc def_pc = (Pc)c->def_pc;
    Pc use_pc = (Pc)c->use_pc;
    if (def_pc >= end || use_pc >= end || consumed[def_pc] || consumed[use_pc])
        return false;
    if (opt_pc_is_target(targets, 1, end, def_pc) ||
        opt_pc_is_target(targets, 1, end, use_pc))
        return false;

    int mul_rd, mul_rs1, mul_rs2;
    DECODE_RRR(vm->text_seg[def_pc + 1], mul_rd, mul_rs1, mul_rs2);
    if (mul_rd != c->reg || mul_rd == REG_ZERO)
        return false;

    int add_rd, add_rs1, add_rs2;
    DECODE_RRR(vm->text_seg[use_pc + 1], add_rd, add_rs1, add_rs2);
    if (c->use_byte != OPT_P_RS1 && c->use_byte != OPT_P_RS2)
        return false;
    int addend = (c->use_byte == OPT_P_RS1) ? add_rs2 : add_rs1;

    set_rrrr_replacement(repls, def_pc, MULADD3, add_rd, addend, mul_rs1,
                         mul_rs2);
    emit_mov_nop(vm, use_pc);
    consumed[def_pc] = true;
    consumed[use_pc] = true;
    return true;
}

static bool opt_fuse_muli3_add3(VirtualMachine *vm, const CcFusionCandidate *c,
                                OptReplacement *repls, bool *consumed,
                                Pc end, const bool *targets) {
    if (c->def_op != MULI3 || c->use_op != ADD3)
        return false;
    Pc def_pc = (Pc)c->def_pc;
    Pc use_pc = (Pc)c->use_pc;
    if (def_pc >= end || use_pc >= end || consumed[def_pc] || consumed[use_pc])
        return false;
    if (opt_pc_is_target(targets, 1, end, def_pc) ||
        opt_pc_is_target(targets, 1, end, use_pc))
        return false;

    int mul_rd, mul_rs;
    DECODE_RR(vm->text_seg[def_pc + 1], mul_rd, mul_rs);
    if (mul_rd != c->reg || mul_rd == REG_ZERO)
        return false;
    long long imm = cc_read_i64_at(vm, def_pc + 2);

    int add_rd, add_rs1, add_rs2;
    DECODE_RRR(vm->text_seg[use_pc + 1], add_rd, add_rs1, add_rs2);
    if (c->use_byte != OPT_P_RS1 && c->use_byte != OPT_P_RS2)
        return false;
    int base = (c->use_byte == OPT_P_RS1) ? add_rs2 : add_rs1;

    set_rrri_replacement(repls, def_pc, MULADDI3, add_rd, base, mul_rs, imm);
    emit_mov_nop(vm, use_pc);
    consumed[def_pc] = true;
    consumed[use_pc] = true;
    return true;
}

static bool opt_fuse_fmul3_fadd3(VirtualMachine *vm, const CcFusionCandidate *c,
                                  OptReplacement *repls, bool *consumed,
                                  Pc end, const bool *targets) {
    bool is_f32 = (c->def_op == FMUL3_F32);
    if ((c->def_op != FMUL3 && c->def_op != FMUL3_F32) ||
        (c->use_op != FADD3 && c->use_op != FADD3_F32))
        return false;
    if ((c->def_op == FMUL3_F32) != (c->use_op == FADD3_F32))
        return false;
    Pc def_pc = (Pc)c->def_pc;
    Pc use_pc = (Pc)c->use_pc;
    if (def_pc >= end || use_pc >= end || consumed[def_pc] || consumed[use_pc])
        return false;
    if (opt_pc_is_target(targets, 1, end, def_pc) ||
        opt_pc_is_target(targets, 1, end, use_pc))
        return false;

    int mul_rd, mul_rs1, mul_rs2;
    DECODE_RRR(vm->text_seg[def_pc + 1], mul_rd, mul_rs1, mul_rs2);
    if (mul_rd != c->reg || mul_rd == REG_ZERO)
        return false;

    int add_rd, add_rs1, add_rs2;
    DECODE_RRR(vm->text_seg[use_pc + 1], add_rd, add_rs1, add_rs2);
    if (c->use_byte != OPT_P_RS1 && c->use_byte != OPT_P_RS2)
        return false;
    int addend = (c->use_byte == OPT_P_RS1) ? add_rs2 : add_rs1;

    int fused_op = vm->compiler.ffp_contract_fma
                   ? (is_f32 ? FMADD3_F32_FMA : FMADD3_FMA)
                   : (is_f32 ? FMADD3_F32     : FMADD3);

    set_rrrr_replacement(repls, def_pc, fused_op, add_rd, addend, mul_rs1,
                         mul_rs2);
    emit_mov_nop(vm, use_pc);
    consumed[def_pc] = true;
    consumed[use_pc] = true;
    return true;
}

static bool opt_fuse_fmul3_fsub3(VirtualMachine *vm, const CcFusionCandidate *c,
                                  OptReplacement *repls, bool *consumed,
                                  Pc end, const bool *targets) {
    bool is_f32 = (c->def_op == FMUL3_F32);
    if ((c->def_op != FMUL3 && c->def_op != FMUL3_F32) ||
        (c->use_op != FSUB3 && c->use_op != FSUB3_F32))
        return false;
    if ((c->def_op == FMUL3_F32) != (c->use_op == FSUB3_F32))
        return false;
    Pc def_pc = (Pc)c->def_pc;
    Pc use_pc = (Pc)c->use_pc;
    if (def_pc >= end || use_pc >= end || consumed[def_pc] || consumed[use_pc])
        return false;
    if (opt_pc_is_target(targets, 1, end, def_pc) ||
        opt_pc_is_target(targets, 1, end, use_pc))
        return false;

    int mul_rd, mul_rs1, mul_rs2;
    DECODE_RRR(vm->text_seg[def_pc + 1], mul_rd, mul_rs1, mul_rs2);
    if (mul_rd != c->reg || mul_rd == REG_ZERO)
        return false;

    // Only fuse the form where the mul result is the minuend: sub_rd = mul_rd - subtrahend.
    // The negated form (subtrahend - mul_rd) is skipped.
    if (c->use_byte != OPT_P_RS1)
        return false;
    int sub_rd, sub_rs1, sub_rs2;
    DECODE_RRR(vm->text_seg[use_pc + 1], sub_rd, sub_rs1, sub_rs2);
    (void)sub_rs1; /* known to equal mul_rd; only sub_rs2 (subtrahend) is needed */
    int subtrahend = sub_rs2;

    int fused_op = vm->compiler.ffp_contract_fma
                   ? (is_f32 ? FMSUB3_F32_FMA : FMSUB3_FMA)
                   : (is_f32 ? FMSUB3_F32     : FMSUB3);

    set_rrrr_replacement(repls, def_pc, fused_op, sub_rd, subtrahend, mul_rs1,
                         mul_rs2);
    emit_mov_nop(vm, use_pc);
    consumed[def_pc] = true;
    consumed[use_pc] = true;
    return true;
}

static bool opt_fuse_fmul3_fnmsub3(VirtualMachine *vm, const CcFusionCandidate *c,
                                   OptReplacement *repls, bool *consumed,
                                   Pc end, const bool *targets) {
    bool is_f32 = (c->def_op == FMUL3_F32);
    if ((c->def_op != FMUL3 && c->def_op != FMUL3_F32) ||
        (c->use_op != FSUB3 && c->use_op != FSUB3_F32))
        return false;
    if ((c->def_op == FMUL3_F32) != (c->use_op == FSUB3_F32))
        return false;
    Pc def_pc = (Pc)c->def_pc;
    Pc use_pc = (Pc)c->use_pc;
    if (def_pc >= end || use_pc >= end || consumed[def_pc] || consumed[use_pc])
        return false;
    if (opt_pc_is_target(targets, 1, end, def_pc) ||
        opt_pc_is_target(targets, 1, end, use_pc))
        return false;

    int mul_rd, mul_rs1, mul_rs2;
    DECODE_RRR(vm->text_seg[def_pc + 1], mul_rd, mul_rs1, mul_rs2);
    if (mul_rd != c->reg || mul_rd == REG_ZERO)
        return false;

    // Only fuse the accumulating-subtract form: sub_rd = minuend - mul_rd.
    // (The minuend form mul_rd - subtrahend is handled by opt_fuse_fmul3_fsub3.)
    if (c->use_byte != OPT_P_RS2)
        return false;
    int sub_rd, sub_rs1, sub_rs2;
    DECODE_RRR(vm->text_seg[use_pc + 1], sub_rd, sub_rs1, sub_rs2);
    (void)sub_rs2; /* known to equal mul_rd; only sub_rs1 (minuend) is needed */
    int minuend = sub_rs1;

    int fused_op = vm->compiler.ffp_contract_fma
                   ? (is_f32 ? FNMSUB3_F32_FMA : FNMSUB3_FMA)
                   : (is_f32 ? FNMSUB3_F32     : FNMSUB3);

    // FNMSUB3 encoding: rd = rs1 - rs2*rs3  →  rs1=minuend, rs2/rs3=mul factors
    set_rrrr_replacement(repls, def_pc, fused_op, sub_rd, minuend, mul_rs1,
                         mul_rs2);
    emit_mov_nop(vm, use_pc);
    consumed[def_pc] = true;
    consumed[use_pc] = true;
    return true;
}

static bool opt_fuse_li3_muladd3(VirtualMachine *vm,
                                 const CcFusionCandidate *c,
                                 OptReplacement *repls, bool *consumed,
                                 Pc end, const bool *targets) {
    if (c->def_op != LI3 || c->use_op != MULADD3)
        return false;
    Pc def_pc = (Pc)c->def_pc;
    Pc use_pc = (Pc)c->use_pc;
    if (def_pc >= end || use_pc >= end || consumed[def_pc] || consumed[use_pc])
        return false;
    if (opt_pc_is_target(targets, 1, end, def_pc) ||
        opt_pc_is_target(targets, 1, end, use_pc))
        return false;

    int imm_reg = vm->text_seg[def_pc + 1] & 0xFF;
    if (imm_reg != c->reg || imm_reg == REG_ZERO)
        return false;
    long long imm = cc_read_i64_at(vm, def_pc + 2);

    int rd, addend, mul_lhs, mul_rhs;
    DECODE_RRRR(vm->text_seg[use_pc + 1], rd, addend, mul_lhs, mul_rhs);
    if (c->use_byte != OPT_P_RS2 && c->use_byte != OPT_P_RS3)
        return false;
    int index = (c->use_byte == OPT_P_RS2) ? mul_rhs : mul_lhs;
    if (index == imm_reg)
        return false;

    set_rrri_replacement(repls, def_pc, MULADDI3, rd, addend, index, imm);
    emit_mov_nop(vm, use_pc);
    consumed[def_pc] = true;
    consumed[use_pc] = true;
    return true;
}

static bool opt_fuse_round(VirtualMachine *vm, int *out_count) {
    if (out_count)
        *out_count = 0;
    if (!vm || !vm->text_seg || !vm->text_ptr)
        return false;

    Pc start = 1;
    Pc end = vm->text_ptr + 1;
    CcAnalyzeFusionOptions opts = {.top_n = INT_MAX, .json = false};
    CcFusionState *st = cc_analyze_fusion_begin(&opts);
    cc_analyze_fusion_feed(st, vm->text_seg, (long long)end, "<optimizer>",
                           NULL);
    int ncands = 0;
    CcFusionCandidate *cands = cc_analyze_fusion_collect(st, &ncands);
    cc_analyze_fusion_finish(st, NULL);

    if (!cands || ncands <= 0) {
        free(cands);
        return false;
    }

    OptReplacement *repls = calloc((size_t)end + 1, sizeof(OptReplacement));
    bool *consumed = calloc((size_t)end + 1, sizeof(bool));
    bool *targets = build_control_flow_targets(vm, start, end);
    if (!repls || !consumed || !targets)
        error("out of memory");

    int fused = 0;
    for (int i = 0; i < ncands; i++) {
        const CcFusionCandidate *c = &cands[i];
        bool ok = opt_fuse_li3_arith(vm, c, repls, consumed, start, end,
                                     targets) ||
                  opt_fuse_li3_muladd3(vm, c, repls, consumed, end, targets) ||
                  opt_fuse_mul3_add3(vm, c, repls, consumed, end, targets) ||
                  opt_fuse_muli3_add3(vm, c, repls, consumed, end, targets) ||
                  opt_fuse_fmul3_fadd3(vm, c, repls, consumed, end, targets) ||
                  opt_fuse_fmul3_fsub3(vm, c, repls, consumed, end, targets) ||
                  opt_fuse_fmul3_fnmsub3(vm, c, repls, consumed, end, targets);
        if (ok)
            fused++;
    }

    if (fused > 0)
        opt_compact_bytecode(vm, repls);

    free(targets);
    free(consumed);
    free(repls);
    free(cands);
    if (out_count)
        *out_count = fused;
    return fused > 0;
}

static void opt_fuse_ops(VirtualMachine *vm) {
    int total = 0;
    for (;;) {
        int fused = 0;
        if (!opt_fuse_round(vm, &fused))
            break;
        total += fused;
    }
    if (vm->debug_vm && total > 0)
        printf("[opt] fused ops: rewrote %d adjacent def-use pair%s\n",
               total, total == 1 ? "" : "s");
}

// ========== Main Entry Point ==========

// Convert an -O level to the default bitmask of passes it enables.
// Levels are cumulative: each level includes all lower-level passes.
//   L1: fold
//   L2: +peephole, +cse
//   L3: +copy-prop, +dce
//   L4: +fuse  (also enabled explicitly by -ffuse)
static uint32_t level_to_opt_mask(int level) {
    uint32_t m = 0;
    if (level >= 1) m |= CCCC_OPT_FOLD;
    if (level >= 2) m |= CCCC_OPT_PEEPHOLE | CCCC_OPT_CSE;
    if (level >= 3) m |= CCCC_OPT_COPY_PROP | CCCC_OPT_DCE;
    if (level >= 4) m |= CCCC_OPT_FUSE;
    return m;
}

// Run the NOP-marking optimisation passes (fold / peephole / copy-prop / DCE)
// on [fn_start, fn_end) according to the given pass bitmask.  Called either
// once for the whole segment (fast path) or once per function (per-fn path).
static void run_opt_passes(VirtualMachine *vm, OptReplacement *repls,
                           uint32_t mask, Pc fn_start, Pc fn_end) {
    if (mask & CCCC_OPT_FOLD)      opt_constant_fold(vm, repls, fn_start, fn_end);
    if (mask & CCCC_OPT_PEEPHOLE)  opt_peephole(vm, fn_start, fn_end);
    if (mask & CCCC_OPT_COPY_PROP) opt_copy_prop(vm, fn_start, fn_end);
    if (mask & CCCC_OPT_DCE)       opt_dead_code(vm, fn_start, fn_end);
}

// Run the post-compaction passes (CSE) on [fn_start, fn_end).
// fn_start/fn_end must already be updated by remap_function_metadata.
static void run_post_compact_passes(VirtualMachine *vm, uint32_t mask,
                                    Pc fn_start, Pc fn_end) {
    if (mask & CCCC_OPT_CSE) opt_cse_const_calls(vm, fn_start, fn_end);
}

void cc_optimize(VirtualMachine *vm, int level) {
    bool have_fn_attrs = vm->compiler.have_fn_opt_attrs;

    // Compute the effective pass mask:
    //   base = level-derived defaults (-O<n>)
    //   +    explicit enables  (-f<pass>)
    //   &~   explicit disables (-fno-<pass>)
    uint32_t base_mask = level_to_opt_mask(level);
    uint32_t effective_mask = (base_mask | vm->compiler.opt_f_enable)
                              & ~vm->compiler.opt_f_disable;

    bool do_fuse = (effective_mask & CCCC_OPT_FUSE) != 0;

    if (!vm || !vm->text_seg || (effective_mask == 0 && !have_fn_attrs)) {
        return;
    }

    Pc seg_end = vm->text_ptr + 1;
    OptReplacement *repls = calloc((size_t)seg_end + 1, sizeof(OptReplacement));
    if (!repls)
        error("out of memory");

    if (!have_fn_attrs) {
        // ---- Fast path: whole-segment optimisation (existing behaviour) ----

        run_opt_passes(vm, repls, effective_mask, 1, seg_end);
        opt_compact_bytecode(vm, repls);
        free(repls);

        // CSE for [[gnu::const]] functions.  Runs after compaction so it sees
        // the final, folded bytecode.  Replaces CALL in-place with MOV3.
        if (effective_mask & CCCC_OPT_CSE)
            opt_cse_const_calls(vm, 1, vm->text_ptr + 1);

        if (do_fuse)
            opt_fuse_ops(vm);

    } else {
        // ---- Per-function path: GCC-style — attribute level overrides global ----
        //
        // Phase 1: NOP-marking passes per function, then a single global
        // compaction.  Functions without an optimize attribute use the global
        // effective mask.  Functions with an __attribute__((optimize(N))) always
        // use their own level as the base (GCC semantics), with global -f/-fno-
        // overrides applied on top.
        bool need_fuse = do_fuse;

        for (Obj *fn = vm->compiler.globals; fn; fn = fn->next) {
            if (!fn->is_function || !fn->body || fn->code_addr <= 0)
                continue;
            Pc fn_start = (Pc)fn->code_addr;
            Pc fn_end   = (Pc)fn->code_end_addr;
            if (fn_end <= fn_start)
                continue;

            int eff_level = fn->fn_optimize_set ? fn->fn_optimize_level : level;
            uint32_t fn_mask = (level_to_opt_mask(eff_level) | vm->compiler.opt_f_enable)
                               & ~vm->compiler.opt_f_disable;

            if (fn_mask & CCCC_OPT_FUSE)
                need_fuse = true;

            run_opt_passes(vm, repls, fn_mask, fn_start, fn_end);
        }

        // Single global compaction — updates code_addr/code_end_addr via
        // remap_function_metadata so Phase 2 ranges are correct.
        opt_compact_bytecode(vm, repls);
        free(repls);

        // Phase 2: Post-compaction passes on the (now remapped) per-fn ranges.
        for (Obj *fn = vm->compiler.globals; fn; fn = fn->next) {
            if (!fn->is_function || !fn->body || fn->code_addr <= 0)
                continue;
            Pc fn_start = (Pc)fn->code_addr;
            Pc fn_end   = (Pc)fn->code_end_addr;
            if (fn_end <= fn_start)
                continue;

            int eff_level = fn->fn_optimize_set ? fn->fn_optimize_level : level;
            uint32_t fn_mask = (level_to_opt_mask(eff_level) | vm->compiler.opt_f_enable)
                               & ~vm->compiler.opt_f_disable;
            run_post_compact_passes(vm, fn_mask, fn_start, fn_end);
        }

        // Fuse-ops runs globally if any function requested it.  The fusion
        // candidate analyser naturally respects function boundaries (RET
        // instructions break def-use chains), so this is always correct.
        // NOTE: non-attributed functions at a lower level may also be fused;
        // this is a known approximation.  A per-function fuse pass is tracked
        // as a potential future improvement.
        if (need_fuse)
            opt_fuse_ops(vm);
    }
}
