/*
 * src/std_stub.c -- stage0 stand-in for the embedded-stdlib table.
 *
 * A fresh clone has no src/std.c (a gitignored build artifact regenerated by
 * `./cccc --build build.c` or `sh tools/regen_stdlib.sh`), so the Makefile
 * links the first, stage0 `cccc` against this file instead (see the
 * `STDLIB_SRC` selection in Makefile and build.c's stdlib_regen_step()).
 *
 * All three accessors return 0 here -- the embedded table is empty. This is
 * safe: get_std_header()'s only caller that requires a non-NULL result,
 * tokenize_private_header() (src/preprocess.c), falls back to resolving
 * "cccc/<name>.h" on disk via the normal -I include search path, which
 * `tools/regen_stdlib.sh` already invokes with `-I./include`. Everything
 * else that consults this table (search_include_paths's is_std check,
 * vm.c's get_std_header_name loop) already tolerates a table that knows
 * about nothing.
 *
 * Once stage0 has produced a real src/std.c on disk, the Makefile's
 * self-correcting `STDLIB_SRC` rule stops linking this file at all.
 *
 * Deliberately standalone: <string.h> only, no internal.h (whose
 * get_std_header/get_stdlib_reg_fn_name/get_std_header_name prototypes at
 * internal.h use `const char *`, while the definitions here -- matching
 * src/std.c's generated shape -- use plain `char *`).
 */

#include <string.h>

char *get_std_header(char *filename);
char *get_std_header(char *filename) {
    (void)filename;
    return 0;
}

char *get_stdlib_reg_fn_name(char *header);
char *get_stdlib_reg_fn_name(char *header) {
    (void)header;
    return 0;
}

char *get_std_header_name(int i);
char *get_std_header_name(int i) {
    (void)i;
    return 0;
}
